package com.yupi.template.modelconfig;
import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import com.google.gson.JsonParser;import com.yupi.template.service.image.ImageHttpTransport;
class ReviewRequestTest {
 private ModelSpec spec(String endpoint,String model){return new ModelSpec("id",1,"test","TEXT","compatible",endpoint,model,60,2000,"2K","1:1");}
 @Test void arkReviewDisablesThinkingWithoutIncreasingLimits(){var s=spec("https://ark.cn-beijing.volces.com/api/v3","deepseek-v4-flash-ga-260731");var body=JsonParser.parseString(ManagedChatModel.reviewBody(s,"审稿",1800)).getAsJsonObject();assertEquals("disabled",body.getAsJsonObject("thinking").get("type").getAsString());assertEquals(1800,body.get("max_tokens").getAsInt());assertFalse(body.get("stream").getAsBoolean());}
 @Test void customEndpointsAndOtherModelsKeepTheirProtocol(){assertFalse(ManagedChatModel.reviewBody(spec("https://other.example.com","deepseek-v4-flash"),"审稿",1800).contains("thinking"));assertFalse(ManagedChatModel.reviewBody(spec("https://ark.cn-beijing.volces.com/api/v3","other-model"),"审稿",1800).contains("thinking"));}
 @Test void normalTextCallRemainsUnchangedAndReviewSubmitsOnlyOnce(){var http=mock(SafeModelHttp.class);when(http.post(anyString(),anyString(),anyString(),anyString(),anyInt())).thenReturn(new ImageHttpTransport.Response(200,"{\"choices\":[{\"message\":{\"content\":\"answer\"}}]}","req"));var model=new ManagedChatModel(mock(ModelSettings.class),http);var s=spec("https://ark.cn-beijing.volces.com/api/v3","deepseek-v4-flash");model.complete(s,"test-only","draft",2000);verify(http).post(anyString(),anyString(),anyString(),argThat(b->!b.contains("thinking")),eq(60));clearInvocations(http);assertEquals("answer",model.completeReview(s,"test-only","review",1800).text());verify(http,times(1)).post(anyString(),anyString(),anyString(),argThat(b->b.contains("disabled")),eq(60));}
 @Test void failedReviewDoesNotAutomaticallyRetry(){var http=mock(SafeModelHttp.class);when(http.post(anyString(),anyString(),anyString(),anyString(),anyInt())).thenReturn(new ImageHttpTransport.Response(429,"{}","quota-id"));var model=new ManagedChatModel(mock(ModelSettings.class),http);assertThrows(ManagedChatModel.Failure.class,()->model.completeReview(spec("https://ark.cn-beijing.volces.com/api/v3","deepseek-v4-flash"),"test-only","review",1800));verify(http,times(1)).post(anyString(),anyString(),anyString(),anyString(),eq(60));}
}
