<template>
 <div class="quick-page"><header><h1>选标题、确认大纲，图文自动出稿</h1><p>输入主题 → 选择标题 → 确认大纲 → 流式写作与配图 → 最后一次 AI 建议。</p></header>
 <a-card v-if="!id"><a-textarea v-model:value="topic" :rows="3" :maxlength="200" placeholder="输入文章主题，例如：一个人如何用AI做独立游戏" /><p class="model-label">文字模型：<strong>{{ textModel }}</strong>（后台默认文字配置）</p><div class="controls"><label>配图模型（仅用于图片）<a-select v-model:value="method" :options="options" style="min-width:240px;display:block" /></label><a-button type="primary" size="large" :loading="creating" @click="create">生成标题</a-button></div><small>文字及真实图片调用可能收费；demo 为演示占位，不保证语义匹配。</small></a-card>
 <a-alert v-if="error" type="warning" show-icon :message="error" class="gap" />
 <section v-if="id" class="hud gap"><div><span class="eyebrow">CREATION · LIVE</span><h2>{{ stageLabel }}</h2><p>文字：{{ textModel }}</p><p>{{ connected ? '实时接收正文' : '通过已保存进度恢复' }}</p><a-space wrap><a-button v-if="!terminal" @click="cancel">停止并保留正文</a-button><a-button @click="router.push('/article/'+id)">查看 / 导出</a-button><a-button v-if="terminal" @click="restart">再写一篇</a-button></a-space></div><div class="meter"><div class="orbit" :class="{still:terminal || waitingOutline || waitingTitle}" role="status" :aria-label="stageLabel"><span>{{ imageReady ? '✓' : (waitingOutline || waitingTitle) ? '✎' : '✦' }}</span></div><p>{{ imageReady ? '配图已保存' : imageFailed ? '配图未完成' : waitingTitle ? '等待选择标题' : waitingOutline ? '等待确认大纲' : '正在创作，请稍候' }}</p></div></section>
 <a-card v-if="waitingTitle" title="选择一个标题" class="gap"><a-radio-group v-model:value="selectedTitle" style="display:grid;gap:16px"><a-radio v-for="(item,index) in titleOptions" :key="index" :value="index"><strong>{{ item.mainTitle }}</strong><p>{{ item.subTitle }}</p></a-radio></a-radio-group><div class="controls"><label>后续文字模型<a-select v-model:value="selectedText" :options="textOptions" style="display:block;min-width:260px" :disabled="!!titlePayload" /></label><label>配图数量<a-select v-model:value="imageCount" :options="[1,2,3,4,5].map(n=>({value:n,label:n+' 张'}))" style="display:block;min-width:120px" :disabled="!!titlePayload" /></label></div><p>所选文字模型用于大纲、正文和最后评审；配图按正文段落分布。真实配图按张可能收费。</p><a-button type="primary" :loading="choosingTitle" @click="confirmTitle">使用这个标题，生成大纲</a-button></a-card>
 <a-card v-if="waitingOutline" title="确认大纲" class="gap"><p>可以修改章节标题与要点。确认后自动完成正文、配图与合成，不再中途评审拦截。</p><div v-for="(section,index) in outline" :key="index" class="outline-item"><a-input v-model:value="section.title" :maxlength="200" placeholder="章节标题" /><a-textarea :value="section.points.join('\n')" @change="updatePoints(index,$event)" :rows="3" placeholder="每行一个要点" /></div><a-button type="primary" size="large" :loading="confirming" @click="confirmOutline">确认大纲，生成图文</a-button></a-card>
 <article v-if="shown" class="draft gap"><div v-html="safeMarkdown(shown)"></div><span v-if="!terminal || shown.length < target.length" class="cursor">▍</span></article>
 <QuickMedia v-if="id" :task-id="id" @updated="refresh" />
 <QuickAdvice v-if="id" :task-id="id" @updated="refresh" />
 </div>
</template>
<script setup lang="ts">
import QuickAdvice from '@/components/QuickAdvice.vue'
import QuickMedia from '@/components/QuickMedia.vue'
import {computed,onMounted,onBeforeUnmount,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {safeMarkdown} from '@/utils/safeMarkdown'
import {connectSSE} from '@/utils/sse'
import {fetchRuntime,submitRuntime} from '@/api/runtime'
import request from '@/request'
const route=useRoute(),router=useRouter(),topic=ref(String(route.query.topic||'')),id=ref(String(route.query.taskId||'')),method=ref('DEMO'),creating=ref(false),error=ref(''),connected=ref(false),status=ref('PROCESSING'),phase=ref('Q_TITLE'),target=ref(''),shown=ref(''),imageReady=ref(false),imageFailed=ref(false)
interface Section {section:number;title:string;points:string[]}
const selectedText=ref(''),imageCount=ref(1),textOptions=ref<{value:string;label:string;version?:number}[]>([{value:'',label:'沿用本任务文字模型'}])
const textModel=ref('正在读取…'),titleOptions=ref<{mainTitle:string;subTitle?:string}[]>([]),selectedTitle=ref(0),choosingTitle=ref(false)
let titlePayload:{index:number;requestId:string;expectedStateVersion:number;textConfigId:string;textConfigVersion?:number;imageCount:number}|undefined
const waitingTitle=computed(()=>phase.value==='TITLE_SELECTING'&&!terminal.value)
const outline=ref<Section[]>([]),stateVersion=ref(0),confirming=ref(false)
let confirmPayload:{outline:Section[];requestId:string;expectedStateVersion:number}|undefined
const waitingOutline=computed(()=>phase.value==='OUTLINE_EDITING'&&!terminal.value)
interface Advice {stopReason?:string;review?:{issues:{reason:string;suggestedAction:string}[]}}
const review=ref<Advice>(),options=ref([{value:'DEMO',label:'演示/占位（无需图片Key）',disabled:false},{value:'NANO_BANANA',label:'Gemini（未配置）',disabled:true},{value:'DOUBAO',label:'豆包（未配置）',disabled:true}])
const terminal=computed(()=>['COMPLETED','IMAGES_FAILED','FAILED','CANCELLED','TIMED_OUT','BUDGET_EXHAUSTED','EXTERNAL_UNCERTAIN'].includes(status.value))
const stageLabel=computed(()=>waitingTitle.value?'标题已准备好，请选择':phase.value==='Q_TITLE'?'正在生成标题…':waitingOutline.value?'大纲已准备好，请确认':phase.value==='Q_OUTLINE'?'正在生成大纲…':terminal.value?(status.value==='COMPLETED'?'图文已完成':status.value==='IMAGES_FAILED'?'正文已完成，配图未完成':'已停止，已收到的正文保留'):phase.value==='Q_ADVICE'?'图文已生成，正在给出评审建议': ['Q_IMAGES','IMAGE_GENERATING','MEDIA'].includes(phase.value)?'正在制作并保存配图':'正在写作…')
let source:EventSource|undefined,poll:ReturnType<typeof setTimeout>|undefined,animation=0,closed=false,controller:AbortController|undefined,requestId=crypto.randomUUID(),polling=false
function stop(){source?.close();source=undefined;if(poll)clearTimeout(poll);connected.value=false}
async function refresh(){if(!id.value||closed||polling)return;if(poll)clearTimeout(poll);polling=true;controller=new AbortController();try{const r=await request.get('/article/quick/'+id.value,{signal:controller.signal,timeout:10000});if(r.data.code!==0)throw new Error(r.data.message);const data=r.data.data,a=data.article;status.value=a.status;phase.value=a.phase;if(data.textModel)textModel.value=data.textModel.name+' · '+data.textModel.model;const saved=a.fullContent||a.content||'';if(terminal.value||saved.length>=target.value.length)target.value=saved;review.value=data.review;stateVersion.value=data.stateVersion;titleOptions.value=a.titleOptions||[];if(phase.value==='OUTLINE_EDITING'&&!outline.value.length)outline.value=structuredClone(a.outline||[]);imageReady.value=!!data.media?.slots?.length&&data.media.slots.every((s:{status:string;result?:{url?:string}})=>s.result?.url&&['SUCCESS','DEGRADED'].includes(s.status));imageFailed.value=terminal.value&&!imageReady.value;error.value=({EXTERNAL_UNCERTAIN:'模型请求结果未确认，已收到的正文保留。请核对供应商结果后再决定是否重新创作；系统不会盲目重试。',TIMED_OUT:'执行已超时，已收到的正文保留。',BUDGET_EXHAUSTED:'本轮调用预算已用完，已有图文保留。'} as Record<string,string>)[a.errorMessage]||a.errorMessage||'';if(terminal.value){stop();}}catch{if(!closed)error.value='连接暂时中断，正在读取已保存进度；不会重复提交创作。'}finally{polling=false;if(!closed&&!terminal.value)poll=setTimeout(refresh,2500)}}
function start(){if(closed)return;stop();source=connectSSE(id.value,{onMessage(m){connected.value=true;if(m.type==='QUICK_TEXT'){target.value=m.content;phase.value='Q_BODY'}if(m.type==='QUICK_STAGE'&&m.phase){phase.value=m.phase;}},onError(){connected.value=false},onComplete(){connected.value=false;void refresh()}});void refresh()}
function updatePoints(index:number,event:Event){outline.value[index]!.points=(event.target as HTMLTextAreaElement).value.split('\n').filter(Boolean)}
async function confirmTitle(){choosingTitle.value=true;error.value='';try{if(!titlePayload)titlePayload={index:selectedTitle.value,requestId:crypto.randomUUID(),expectedStateVersion:stateVersion.value,textConfigId:selectedText.value,textConfigVersion:textOptions.value.find(x=>x.value===selectedText.value)?.version,imageCount:imageCount.value};const r=await request.post('/article/quick/'+id.value+'/title',titlePayload);if(r.data.code!==0){titlePayload=undefined;throw new Error(r.data.message)}phase.value='Q_OUTLINE';titlePayload=undefined;start()}catch(e){error.value=e instanceof Error&&!('isAxiosError'in e)?e.message:'确认结果未收到，再次点击复用同一请求编号。'}finally{choosingTitle.value=false}}
async function confirmOutline(){confirming.value=true;error.value='';try{if(!confirmPayload)confirmPayload={outline:JSON.parse(JSON.stringify(outline.value)),requestId:crypto.randomUUID(),expectedStateVersion:stateVersion.value};const r=await request.post('/article/quick/'+id.value+'/outline',confirmPayload);if(r.data.code!==0){confirmPayload=undefined;throw new Error(r.data.message)}phase.value='Q_BODY';confirmPayload=undefined;start()}catch(e){error.value=e instanceof Error&&!('isAxiosError'in e)?e.message:'确认结果未收到，再次点击复用同一请求编号；不会自动重复生成。'}finally{confirming.value=false}}
async function create(){if(!topic.value.trim())return;creating.value=true;error.value='';try{const r=await request.post('/article/quick',{topic:topic.value,enabledImageMethods:[method.value],requestId});if(r.data.code!==0)throw new Error(r.data.message);id.value=r.data.data;await router.replace({path:'/create',query:{taskId:id.value}});start()}catch(e){error.value=e instanceof Error&&!('isAxiosError'in e)?e.message:'创建结果未确认，再次点击将使用同一请求编号，不重复提交。'}finally{creating.value=false}}
async function cancel(){try{const r=await fetchRuntime(id.value);await submitRuntime(id.value,'CANCEL',r.stateVersion);await refresh()}catch{error.value='状态已变化，请稍后重试停止操作。'}}
function restart(){stop();id.value='';target.value='';shown.value='';review.value=undefined;requestId=crypto.randomUUID();status.value='PROCESSING';phase.value='Q_TITLE';titleOptions.value=[];selectedTitle.value=0;titlePayload=undefined;selectedText.value='';imageCount.value=1;outline.value=[];confirmPayload=undefined;imageReady.value=false;imageFailed.value=false;void router.replace('/create')}
function draw(){if(closed)return;if(!target.value.startsWith(shown.value))shown.value=target.value;else if(shown.value.length<target.value.length)shown.value=target.value.slice(0,shown.value.length+Math.max(2,Math.ceil((target.value.length-shown.value.length)/80)));animation=requestAnimationFrame(draw)}
onMounted(async()=>{draw();try{const r=await request.get('/article/quick/text-models');if(r.data.code===0)textOptions.value.push(...r.data.data.map((x:{id:string;name:string;model:string;version:number})=>({value:x.id,label:x.name+' · '+x.model,version:x.version})))}catch{error.value='文字模型列表读取失败，可沿用本任务模型。'}try{const r=await request.get('/article/text-capabilities');textModel.value=r.data.code===0?r.data.data.name+' · '+r.data.data.model:'请管理员检查文字配置'}catch{textModel.value='暂无法读取，请查看模型设置'}try{const r=await request.get('/article/image-capabilities'),c=r.data.data;options.value[1]={value:'NANO_BANANA',label:'Gemini '+(c.geminiConfigured?c.geminiModel:'（未配置）'),disabled:!c.geminiConfigured};options.value[2]={value:'DOUBAO',label:'豆包 '+(c.doubaoConfigured?c.doubaoModel:'（未配置）'),disabled:!c.doubaoConfigured};method.value=c.defaultMethod||'DEMO'}catch{error.value='模型配置读取失败，请管理员检查设置。'}if(id.value)start()})
onBeforeUnmount(()=>{closed=true;stop();controller?.abort();cancelAnimationFrame(animation)})
</script>
<style scoped>
.quick-page{max-width:1000px;margin:0 auto;padding:32px 20px}.quick-page header{text-align:center;margin-bottom:28px}.quick-page header h1{font-size:30px;color:#153e31}.controls{display:flex;flex-wrap:wrap;justify-content:space-between;gap:14px;margin:20px 0}.gap{margin-top:24px}.hud{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:28px;border-radius:20px;background:linear-gradient(120deg,#10382d,#1b5141);color:#ecfdf5}.hud h2{color:white}.eyebrow{letter-spacing:3px;color:#6ee7b7;font-size:12px}.meter{text-align:center;min-width:145px}.orbit{position:relative;width:92px;height:92px;margin:0 auto;border:2px solid #ffffff1c;border-radius:50%;display:grid;place-items:center;box-shadow:0 0 30px #34d39920}.orbit:before,.orbit:after{content:'';position:absolute;inset:-2px;border:3px solid transparent;border-top-color:#6ee7b7;border-right-color:#34d39960;border-radius:50%;animation:orbit 1.4s linear infinite}.orbit:after{inset:8px;border-width:1px;border-top-color:#ffffffb0;animation-direction:reverse;animation-duration:2.5s}.orbit span{font-size:30px;color:#a7f3d0}.orbit.still:before,.orbit.still:after{animation:none;border-color:#34d39955}.outline-item{display:grid;gap:8px;margin:16px 0}@keyframes orbit{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.orbit:before,.orbit:after,.cursor{animation:none}}.meter small{font-size:11px}.draft,.advice{padding:28px;border:1px solid #e3eee8;border-radius:18px;background:white;line-height:1.9;overflow-wrap:anywhere}.draft :deep(img){max-width:100%;border-radius:12px}.draft :deep(pre){overflow:auto}.cursor{color:#10b981;animation:blink 1s steps(2) infinite}.advice{background:#f1faf5}.advice li{margin-bottom:16px}@keyframes blink{to{opacity:0}}@media(max-width:600px){.quick-page{padding:16px 10px}.quick-page header h1{font-size:23px}.hud{padding:18px;align-items:flex-start}.hud h2{font-size:17px}.draft,.advice{padding:18px}.meter{min-width:115px}}
</style>
