package com.yupi.template.service;
import com.yupi.template.service.image.*;import com.yupi.template.config.*;import com.yupi.template.model.dto.image.*;import com.yupi.template.model.enums.ImageMethodEnum;import com.yupi.template.service.impl.ArticleServiceImpl;import com.yupi.template.model.entity.User;
import org.junit.jupiter.api.*;import org.junit.jupiter.params.ParameterizedTest;import org.junit.jupiter.params.provider.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import org.springframework.test.util.ReflectionTestUtils;import org.springframework.boot.test.context.runner.ApplicationContextRunner;import org.springframework.boot.context.properties.EnableConfigurationProperties;import org.springframework.context.annotation.Configuration;import org.springframework.core.env.SystemEnvironmentPropertySource;import java.util.*;import java.io.*;
class A4ImageProviderTest {
 static final String KEY="isolated-test-credential";static String png;
 @BeforeAll static void fixture()throws Exception{var b=new ByteArrayOutputStream();javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(2,2,1),"png",b);png=Base64.getEncoder().encodeToString(b.toByteArray());}
 static ImageProfile profile(String provider){return new ImageProfile(provider,provider.equals("gemini")?"gemini-3.1-flash-image":"account-image-endpoint",provider.equals("gemini")?"https://generativelanguage.googleapis.com":"https://ark.cn-beijing.volces.com/api/v3",provider.equals("gemini")?"1K":"2K","16:9",2048,120);}
 static String response(String provider){return provider.equals("gemini")?"{\"responseId\":\"req-g\",\"candidates\":[{\"content\":{\"parts\":[{\"inlineData\":{\"mimeType\":\"image/png\",\"data\":\""+png+"\"}}]}}],\"usageMetadata\":{\"totalTokenCount\":17}}":"{\"data\":[{\"b64_json\":\""+png+"\"}],\"usage\":{\"generated_images\":1}}";}
 @ParameterizedTest @ValueSource(strings={"gemini","doubao"}) void nativeProtocolAndMetadata(String provider){var http=mock(ImageHttpTransport.class);when(http.post(anyString(),anyString(),anyString(),anyString(),anyInt())).thenReturn(new ImageHttpTransport.Response(200,response(provider),"req-d"));var data=ImageProviderProtocol.generate(http,profile(provider),KEY,"one picture");assertArrayEquals(Base64.getDecoder().decode(png),data.getImageBytes());assertEquals(provider,data.getMetadata().provider());assertFalse(data.getMetadata().usage().isEmpty());verify(http,times(1)).post(contains(provider.equals("gemini")?":generateContent":"/images/generations"),eq(provider.equals("gemini")?"x-goog-api-key":"Authorization"),eq(provider.equals("gemini")?KEY:"Bearer "+KEY),argThat(body->provider.equals("gemini")?body.contains("responseModalities")&&!body.contains("sequential_image_generation"):body.contains("\"sequential_image_generation\":\"disabled\"")&&body.contains("b64_json")),eq(120));}
 @ParameterizedTest @CsvSource({"401,AUTH,false","403,AUTH,false","429,QUOTA,false","400,INVALID_REQUEST,false","500,TRANSPORT,true","408,TRANSPORT,true"}) void categorizedRejections(int status,String category,boolean uncertain){var http=mock(ImageHttpTransport.class);when(http.post(anyString(),anyString(),anyString(),anyString(),anyInt())).thenReturn(new ImageHttpTransport.Response(status,"secret provider body","error-request-id"));var e=assertThrows(ImageProviderException.class,()->ImageProviderProtocol.generate(http,profile("doubao"),KEY,"one"));assertEquals(category,e.category().name());assertEquals(uncertain,e.uncertain());assertEquals("error-request-id",e.requestId());assertFalse(e.getMessage().contains("secret"));verify(http,times(1)).post(anyString(),anyString(),anyString(),anyString(),anyInt());}
 @ParameterizedTest @ValueSource(strings={"gemini","doubao"}) void noImageIsExplicit(String provider){var http=mock(ImageHttpTransport.class);when(http.post(anyString(),anyString(),anyString(),anyString(),anyInt())).thenReturn(new ImageHttpTransport.Response(200,"{}",null));assertEquals(ImageProviderException.Category.NO_IMAGE,assertThrows(ImageProviderException.class,()->ImageProviderProtocol.generate(http,profile(provider),KEY,"one")).category());}
 @Test void malformedSuccessIsUncertain(){var http=mock(ImageHttpTransport.class);when(http.post(anyString(),anyString(),anyString(),anyString(),anyInt())).thenReturn(new ImageHttpTransport.Response(200,"not-json",null));assertTrue(assertThrows(ImageProviderException.class,()->ImageProviderProtocol.generate(http,profile("doubao"),KEY,"one")).uncertain());}
 @Test void endpointCannotTargetPrivateHost(){var p=new ImageProfile("doubao","model","http://127.0.0.1:3333","2K","1:1",2048,120);var http=mock(ImageHttpTransport.class);assertThrows(IllegalArgumentException.class,()->ImageProviderProtocol.generate(http,p,KEY,"one"));verifyNoInteractions(http);}
 @Configuration @EnableConfigurationProperties({NanoBananaConfig.class,DoubaoConfig.class}) static class Binding {}
 @ParameterizedTest @CsvSource({"false,false","true,false","false,true","true,true"}) void realSpringEnvironmentBinding(boolean gemini,boolean doubao){new ApplicationContextRunner().withUserConfiguration(Binding.class).withInitializer(ctx->{try{for(var source:new org.springframework.boot.env.YamlPropertySourceLoader().load("production-yaml",new org.springframework.core.io.ClassPathResource("application-prod.yml")))ctx.getEnvironment().getPropertySources().addLast(source);}catch(IOException e){throw new IllegalStateException(e);}Map<String,Object> env=new HashMap<>();env.put("GEMINI_API_KEY",gemini?KEY:"");env.put("GEMINI_MODEL","gemini-3.1-flash-image");env.put("DOUBAO_API_KEY",doubao?KEY:"");env.put("DOUBAO_MODEL","account-image-endpoint");ctx.getEnvironment().getPropertySources().addFirst(new SystemEnvironmentPropertySource("isolated-env",env));}).run(ctx->{assertNull(ctx.getStartupFailure());assertEquals(gemini,ctx.getBean(NanoBananaConfig.class).configured());assertEquals(doubao,ctx.getBean(DoubaoConfig.class).configured());assertFalse(ctx.getBean(DoubaoConfig.class).toString().contains(KEY));});}
 @Test void doubaoRequiresModelId(){var c=new DoubaoConfig();c.setApiKey(KEY);assertFalse(c.configured());}
 @Test void backendRejectsUnconfiguredAndMixedProviders(){var service=new ArticleServiceImpl();ReflectionTestUtils.setField(service,"modelSettings",mock(com.yupi.template.modelconfig.ModelSettings.class));var g=new NanoBananaConfig();g.setApiKey(KEY);var d=new DoubaoConfig();ReflectionTestUtils.setField(service,"imageConfig",g);ReflectionTestUtils.setField(service,"doubaoConfig",d);var u=new User();u.setUserRole("admin");assertThrows(com.yupi.template.exception.BusinessException.class,()->ReflectionTestUtils.invokeMethod(service,"validateImageMethods",List.of("DOUBAO"),u));d.setApiKey(KEY);d.setModel("account-image-endpoint");assertDoesNotThrow(()->ReflectionTestUtils.invokeMethod(service,"validateImageMethods",List.of("DOUBAO"),u));assertThrows(com.yupi.template.exception.BusinessException.class,()->ReflectionTestUtils.invokeMethod(service,"validateImageMethods",List.of("DOUBAO","NANO_BANANA"),u));}
 @Test void persistedSelectionSurvivesConfigurationChange(){var jdbc=mock(org.springframework.jdbc.core.JdbcTemplate.class);var g=new NanoBananaConfig();var d=new DoubaoConfig();d.setModel("first-model");var store=new ImageProfileStore(jdbc,g,d);var frozen=store.snapshot("DOUBAO");when(jdbc.queryForList(anyString(),anyString(),anyString())).thenReturn(List.of(Map.of("profileJson",com.yupi.template.utils.GsonUtils.toJson(frozen))));d.setModel("other-model");assertEquals("first-model",store.find("task","DOUBAO").model());assertEquals("doubao",store.find("task","DOUBAO").provider());}
 @Test void httpTransportTimesOutWithoutResubmission()throws Exception{var server=com.sun.net.httpserver.HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);var count=new java.util.concurrent.atomic.AtomicInteger();server.createContext("/",x->{count.incrementAndGet();try{Thread.sleep(1800);}catch(InterruptedException e){Thread.currentThread().interrupt();}x.close();});server.start();try{var e=assertThrows(ImageProviderException.class,()->new ImageHttpTransport().post("http://127.0.0.1:"+server.getAddress().getPort()+"/","x-test",KEY,"{}",1));assertTrue(e.uncertain());assertEquals(1,count.get());}finally{server.stop(0);}}
 @Test void selectedAdapterDoesNotCallOtherSupplier(){var strategy=new ImageServiceStrategy();var g=mock(NanoBananaService.class);var d=mock(DoubaoImageService.class);when(g.getMethod()).thenReturn(ImageMethodEnum.NANO_BANANA);when(d.getMethod()).thenReturn(ImageMethodEnum.DOUBAO);when(d.isAvailable()).thenReturn(true);when(d.getImageData(any())).thenThrow(new ImageProviderException(ImageProviderException.Category.QUOTA,false));ReflectionTestUtils.setField(strategy,"imageSearchServices",List.of(g,d));ReflectionTestUtils.setField(strategy,"generated",mock(com.yupi.template.storage.GeneratedImageStore.class));strategy.init();assertThrows(ImageProviderException.class,()->strategy.getImageAndUpload("DOUBAO",ImageRequest.builder().profile(profile("doubao")).prompt("one").build()));verify(g,never()).getImageData(any());verify(d,times(1)).getImageData(any());}

 @ParameterizedTest @ValueSource(strings={"gemini","doubao"}) void realHttpProtocolToLocalStorage(String provider)throws Exception{
  var server=com.sun.net.httpserver.HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);var submissions=new java.util.concurrent.atomic.AtomicInteger();server.createContext("/",x->{submissions.incrementAndGet();String body=new String(x.getRequestBody().readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);assertTrue(body.contains("one picture"));byte[] response=response(provider).getBytes(java.nio.charset.StandardCharsets.UTF_8);x.sendResponseHeaders(200,response.length);x.getResponseBody().write(response);x.close();});server.start();
  java.nio.file.Path dir=java.nio.file.Files.createTempDirectory("image-provider-test");try{var http=new ImageHttpTransport(){@Override public Response post(String url,String header,String key,String json,int timeout){return super.post("http://127.0.0.1:"+server.getAddress().getPort()+"/",header,key,json,timeout);}};var data=ImageProviderProtocol.generate(http,profile(provider),KEY,"one picture");var local=new com.yupi.template.storage.LocalImageStorage(dir.toString(),5242880);String url=local.save(data,"images");assertTrue(com.yupi.template.storage.ImageReferences.local(url));assertArrayEquals(data.getImageBytes(),local.read(url.substring(12)));assertEquals(1,submissions.get());}finally{server.stop(0);try(var files=java.nio.file.Files.list(dir)){for(var file:files.toList())java.nio.file.Files.delete(file);}java.nio.file.Files.delete(dir);}
 }
 @ParameterizedTest @ValueSource(booleans={false,true}) void runtimePersistsProviderErrorWithoutSwitching(boolean uncertain){var ledger=mock(com.yupi.template.runtime.RuntimeLedger.class);var store=mock(com.yupi.template.runtime.RuntimeStore.class);var ticket=new com.yupi.template.runtime.RuntimeScope.Ticket("task","request","run",1);when(ledger.prepare(any(),any(),any(),any())).thenReturn(new com.yupi.template.runtime.RuntimeLedger.Call("a".repeat(64),true,"IN_FLIGHT",null,null,System.currentTimeMillis()+5000));var failure=new ImageProviderException(uncertain?ImageProviderException.Category.TIMEOUT:ImageProviderException.Category.AUTH,uncertain);var runtime=new com.yupi.template.runtime.RuntimeExternal(ledger,store,List.of());var count=new java.util.concurrent.atomic.AtomicInteger();var thrown=assertThrows(RuntimeException.class,()->runtime.call(ticket,"IMAGE:1","image:DOUBAO","{}",()->{count.incrementAndGet();throw failure;}));if(uncertain)assertEquals("EXTERNAL_UNCERTAIN",assertInstanceOf(com.yupi.template.runtime.RuntimeStop.class,thrown).status);else assertSame(failure,thrown);assertEquals(1,count.get());verify(ledger).imageRejected(ticket,"a".repeat(64),failure);}
}
