package com.yupi.template.service;
import org.junit.jupiter.api.Test;import org.junit.jupiter.params.ParameterizedTest;import org.junit.jupiter.params.provider.ValueSource;import static org.junit.jupiter.api.Assertions.*;import java.util.*;import com.yupi.template.model.dto.article.*;import com.yupi.template.agent.review.*;
class PlacementAndReviewSkillTest {
 private ArticleState article(){var s=new ArticleState();s.setTopic("幼儿园中秋活动");s.setUserDescription("给教师执行，勿编造实际活动成果");s.setEnabledImageMethods(List.of("DOUBAO"));var title=new ArticleState.TitleResult();title.setMainTitle("五站中秋游园");s.setTitle(title);s.setContent("## 寻月\n\n观察月亮的形状。\n\n## 探月\n\n用纸盘观察卡记录变化。\n\n## 赏月\n\n一起欣赏月亮诗歌。\n\n## 绘月\n\n画出自己想象的月亮。\n\n## 团圆\n\n展示作品，分享团圆故事。");return s;}
 @ParameterizedTest @ValueSource(ints={1,2,3,4,5}) void countAndAnchorAreDeterministic(int count){var s=article();var plan=ArticleImagePlacement.plan(s,count);assertEquals(count,plan.size());assertEquals(count,plan.stream().map(ArticleState.ImageRequirement::getAfterParagraphId).distinct().count());for(var req:plan){var paragraph=new ParagraphDraft(s.getContent()).paragraphs().stream().filter(p->p.sectionId().equals(req.getAfterParagraphId())).findFirst().orElseThrow();assertTrue(req.getPrompt().contains(paragraph.text()));assertFalse(paragraph.text().startsWith("#"));}assertEquals(plan.stream().map(ArticleState.ImageRequirement::getPrompt).toList(),ArticleImagePlacement.plan(s,count).stream().map(ArticleState.ImageRequirement::getPrompt).toList());}
 @Test void renderPreservesTextAndRetryPosition(){var s=article();var plan=ArticleImagePlacement.plan(s,3);var slots=new ArrayList<MediaState.Slot>();var images=new LinkedHashMap<String,String>();for(int i=0;i<3;i++){String id="image-"+i;slots.add(new MediaState.Slot(id,plan.get(i),null,"PENDING",0,null));images.put(id,"![图](test-"+i+")");}var m=new MediaState(s.getContent(),slots);String rendered=ArticleImagePlacement.render(m,images);assertEquals(s.getContent(),rendered.replaceAll("\\n\\n!\\[图\\]\\(test-\\d\\)",""));images.put("image-1","![图](replacement)");assertEquals(rendered.replace("test-1","replacement"),ArticleImagePlacement.render(m,images));assertEquals(s.getContent(),m.template());}
 @Test void noAnchorInsideCodeFence(){var s=article();s.setContent("引言。\n\n```java\n\ncode();\n\n```\n\n结尾。");var ids=new ParagraphDraft(s.getContent()).paragraphs();for(var r:ArticleImagePlacement.plan(s,2))assertTrue(ids.stream().filter(p->p.sectionId().equals(r.getAfterParagraphId())).allMatch(p->!p.text().contains("code")));}
 @Test void skillIncludesBriefWithoutClaimingToSeeImages(){var s=article();String prompt=AdvisoryReviewSkill.prompt(s,null);assertTrue(prompt.contains(s.getUserDescription()));assertTrue(prompt.contains(s.getTitle().getMainTitle()));assertTrue(prompt.contains("未提供图片像素"));assertTrue(prompt.contains("计划时长"));assertTrue(prompt.contains("p2"));}
 @Test void invalidCountsRejected(){assertThrows(IllegalArgumentException.class,()->ArticleImagePlacement.plan(article(),0));assertThrows(IllegalArgumentException.class,()->ArticleImagePlacement.plan(article(),6));}
}
