<template><section v-if="quick && (review || phase==='Q_ADVICE')" class="quick-advice"><h3>AI 评审建议</h3><p>仅供参考，不阻断成稿，不代表事实已经核验。</p><p v-if="busy && phase==='Q_ADVICE'"><span class="ring" />正在评审，图文已保留…</p><p v-else-if="review?.stopReason">{{ review.stopReason }}</p><ul v-if="review?.review?.issues?.length"><li v-for="(issue,i) in review.review.issues" :key="i"><b>{{ issue.reason }}</b><p>{{ issue.suggestedAction }}</p></li></ul><p v-else-if="review?.review">本次未提出修改建议；不等于事实全部正确。</p><a-button v-if="review && !review.review" :disabled="busy" @click="ack=false;open=true">仅重新评审</a-button><p v-if="error">{{ error }}</p><a-modal v-model:open="open" title="仅重新评审" ok-text="确认并评审" :confirm-loading="submitting" :ok-button-props="{disabled:!ack}" @ok="retry"><p>仅调用本任务固定的文字模型一次，不重新生成正文或图片，仍受本轮剩余预算限制。</p><a-checkbox v-model:checked="ack">确认可能产生文字调用费用；之前超时的请求也可能已经收费。</a-checkbox></a-modal></section></template>
<script setup lang="ts">
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import request from '@/request'
const props=defineProps<{taskId:string}>(),emit=defineEmits<{mode:[boolean];updated:[]}>(),quick=ref(false),review=ref<{stopReason?:string;review?:{issues:{reason:string;suggestedAction:string}[]}}>(),phase=ref(''),status=ref(''),version=ref(0),open=ref(false),ack=ref(false),submitting=ref(false),error=ref('')
const busy=computed(()=>['PROCESSING','RECOVERING'].includes(status.value))
let disposed=false,timer:ReturnType<typeof setTimeout>|undefined,abort:AbortController|undefined,payload:{requestId:string;expectedStateVersion:number;acknowledgeCost:boolean}|undefined
async function load(){if(disposed)return;if(timer)clearTimeout(timer);abort=new AbortController();try{const r=await request.get('/article/quick/'+props.taskId,{signal:abort.signal,timeout:10000});if(disposed)return;if(r.data.code!==0)throw Error();const d=r.data.data;quick.value=d.quick;review.value=d.review;phase.value=d.article.phase;status.value=d.article.status;const changed=version.value!==d.stateVersion;version.value=d.stateVersion;emit('mode',quick.value);if(changed)emit('updated')}catch{if(!disposed)error.value='评审状态暂时读取失败，请刷新页面。'}finally{if(!disposed&&(!status.value||busy.value))timer=setTimeout(load,2500)}}
async function retry(){if(!ack.value||submitting.value)return;submitting.value=true;error.value='';try{payload ||= {requestId:crypto.randomUUID(),expectedStateVersion:version.value,acknowledgeCost:true};const r=await request.post('/article/quick/'+props.taskId+'/advice-retry',payload);if(r.data.code!==0){payload=undefined;throw Error(r.data.message)}payload=undefined;open.value=false;await load()}catch(e){error.value=e instanceof Error&&!('isAxiosError'in e)?e.message:'确认结果未收到，再次确认复用同一请求编号，不自动重复调用。'}finally{submitting.value=false}}
onMounted(load);onBeforeUnmount(()=>{disposed=true;abort?.abort();if(timer)clearTimeout(timer)})
</script>
<style scoped>.quick-advice{margin-top:24px;padding:24px;background:#f1faf5;border:1px solid #d8eee2;border-radius:18px}.quick-advice p{line-height:1.8}.ring{display:inline-block;width:18px;height:18px;border:2px solid #d0eadd;border-top-color:#10b981;border-radius:50%;animation:spin 1s linear infinite;vertical-align:middle;margin-right:8px}@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.ring{animation:none}}</style>
