<template><section v-if="quick && slots.length" class="media-panel"><h2>配图</h2><div v-for="slot in slots" :key="slot.id" class="media-slot"><img v-if="slot.result?.url" :src="slot.result.url" alt="文章配图" /><div v-else class="missing"><span v-if="busy" class="ring" />{{ busy ? '正在处理配图…' : '配图暂缺' }}</div><div><strong>{{ slot.requirement.sectionTitle || '配图' }}</strong><p>图片供应商：{{ slot.requirement.profile?.provider || slot.requirement.imageSource }} · {{ slot.requirement.profile?.model || '演示占位' }}</p><p v-if="slot.status==='DEGRADED'">演示/占位，不保证语义匹配。</p><p v-if="slot.error" class="error">{{ slot.error }}</p><a-button :disabled="busy || !canRetry" @click="openRetry(slot)">重试 / 修改提示词</a-button></div></div><p v-if="message" class="error">{{ message }}</p><a-modal v-model:open="open" title="单张配图重试" ok-text="确认并执行" :confirm-loading="submitting" :ok-button-props="{disabled: !ack}" @ok="submit"><p>不修改提示词时优先复用已缓存结果、重新保存；修改提示词会重新生图。正文和其他图片保持不变。</p><a-textarea v-model:value="prompt" :rows="5" :maxlength="4000" :disabled="!!payload" /><p>已有成功图片会优先复用；如需新画面，请修改提示词。图片可能因本地大小限制适当缩小。</p><a-checkbox v-model:checked="ack">我确认执行：真实模型可能收费；若上次结果不确定，也可能已收费。不会自动切换供应商。</a-checkbox></a-modal></section></template>
<script setup lang="ts">
import {ref,computed,onMounted,onBeforeUnmount,watch} from 'vue'
import request from '@/request'
interface Slot {id:string;status:string;error?:string;result?:{url?:string};requirement:{prompt?:string;sectionTitle?:string;imageSource:string;profile?:{provider:string;model:string}}}
const props=defineProps<{taskId:string}>(),emit=defineEmits(['updated']),slots=ref<Slot[]>([]),quick=ref(false),status=ref(''),version=ref(0),open=ref(false),prompt=ref(''),ack=ref(false),submitting=ref(false),message=ref(''),selected=ref('')
const busy=computed(()=>['PROCESSING','RECOVERING'].includes(status.value)),canRetry=computed(()=>['COMPLETED','IMAGES_FAILED'].includes(status.value))
let timer:ReturnType<typeof setTimeout>|undefined,disposed=false,controller:AbortController|undefined
const payload=ref<{imageId:string;prompt:string;requestId:string;expectedStateVersion:number;acknowledgeCost:boolean}>()
async function load(){if(disposed||!props.taskId)return;const task=props.taskId;if(timer)clearTimeout(timer);controller=new AbortController();try{const r=await request.get('/article/quick/'+task,{signal:controller.signal,timeout:10000});if(disposed||task!==props.taskId)return;if(r.data.code!==0)throw Error();const d=r.data.data;quick.value=d.quick;slots.value=d.media?.slots||[];const changed=status.value!==d.article.status||version.value!==d.stateVersion;status.value=d.article.status;version.value=d.stateVersion;if(changed)emit('updated',d.article)}catch{if(!disposed)message.value='配图状态暂时无法读取，请刷新页面。'}finally{if(!disposed&&task===props.taskId&&(!status.value||busy.value))timer=setTimeout(load,2500)}}
function openRetry(slot:Slot){selected.value=slot.id;prompt.value=slot.requirement.prompt||'';ack.value=false;payload.value=undefined;open.value=true}
async function submit(){if(!ack.value||submitting.value)return;submitting.value=true;message.value='';try{payload.value ||= {imageId:selected.value,prompt:prompt.value,requestId:crypto.randomUUID(),expectedStateVersion:version.value,acknowledgeCost:true};const r=await request.post('/article/quick/'+props.taskId+'/image-retry',payload.value);if(r.data.code!==0){payload.value=undefined;throw new Error(r.data.message)}open.value=false;payload.value=undefined;await load()}catch(e){message.value=e instanceof Error&&!('isAxiosError'in e)?e.message:'请求结果未收到，请勿反复新建重试；再次确认将复用本次请求编号。'}finally{submitting.value=false}}
watch(()=>props.taskId,()=>{controller?.abort();slots.value=[];status.value='';void load()})
onMounted(load);onBeforeUnmount(()=>{disposed=true;controller?.abort();if(timer)clearTimeout(timer)})
</script>
<style scoped>.media-panel{margin-top:24px;padding:24px;border:1px solid #dceee5;border-radius:18px;background:#fbfefc}.media-slot{display:flex;gap:22px;align-items:center;flex-wrap:wrap;margin:16px 0}.media-slot img,.missing{width:220px;max-width:100%;border-radius:12px}.missing{height:150px;background:#edf6f1;display:flex;align-items:center;justify-content:center;gap:10px}.error{color:#a65e20;overflow-wrap:anywhere}.ring{width:24px;height:24px;border:3px solid #cee9dd;border-top-color:#10b981;border-radius:50%;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.ring{animation:none}}@media(max-width:600px){.media-slot{display:block}.media-panel{padding:16px}}</style>
