package com.yupi.template.storage;
import org.springframework.stereotype.Service;import org.springframework.jdbc.core.JdbcTemplate;import lombok.RequiredArgsConstructor;import com.yupi.template.model.dto.image.ImageData;import com.yupi.template.runtime.*;
@Service @RequiredArgsConstructor public class GeneratedImageStore {
 private final JdbcTemplate jdbc;
 public String key(String payload){return RuntimeScope.active()?RuntimeExternal.hash(RuntimeScope.current().ticket().taskId()+"\n"+payload):null;}
 public String key(String taskId,String payload){return taskId==null?key(payload):RuntimeExternal.hash(taskId+"\n"+payload);}
 public ImageData find(String key){if(key==null)return null;var rows=jdbc.queryForList("SELECT imageBytes,mimeType FROM article_generated_image WHERE cacheKey=?",key);if(rows.isEmpty())return null;var data=ImageData.fromBytes((byte[])rows.getFirst().get("imageBytes"),(String)rows.getFirst().get("mimeType"));var metadata=jdbc.queryForList("SELECT metadataJson FROM article_image_metadata WHERE cacheKey=?",key);if(!metadata.isEmpty())data.setMetadata(com.yupi.template.utils.GsonUtils.fromJson((String)metadata.getFirst().get("metadataJson"),com.yupi.template.service.image.ImageMetadata.class));return data;}
 @org.springframework.transaction.annotation.Transactional public void save(String key,ImageData data){save(key,data,RuntimeScope.active()?RuntimeScope.current().ticket().taskId():null);}
 @org.springframework.transaction.annotation.Transactional public void save(String key,ImageData data,String taskId){if(key==null)return;if(taskId==null)throw new IllegalArgumentException("Image cache owner missing");RuntimeScope.guard();byte[] bytes=data.getImageBytes();if(bytes==null||bytes.length>5242880)throw new RuntimeStop("EXTERNAL_UNCERTAIN");try{jdbc.update("INSERT IGNORE INTO article_generated_image(cacheKey,taskId,imageBytes,mimeType) VALUES (?,?,?,?)",key,taskId,bytes,data.getMimeType());if(data.getMetadata()!=null)jdbc.update("INSERT IGNORE INTO article_image_metadata(cacheKey,metadataJson) VALUES (?,?)",key,com.yupi.template.utils.GsonUtils.toJson(data.getMetadata()));}catch(Exception e){throw new RuntimeStop("EXTERNAL_UNCERTAIN");}}
}
