package com.yupi.template.runtime;
import com.yupi.template.model.dto.article.*;import com.yupi.template.utils.GsonUtils;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.jdbc.core.JdbcTemplate;import java.util.*;
@Service @lombok.RequiredArgsConstructor public class QuickCreationStore {
 private final JdbcTemplate jdbc;private final RuntimeStore store;private final com.yupi.template.repository.ReviewTraceStore reviews;
 @Transactional public void outline(RuntimeScope.Ticket t,ArticleState.OutlineResult outline){store.guard(t);jdbc.update("UPDATE article SET mainTitle=COALESCE(mainTitle,topic),outline=?,phase='OUTLINE_EDITING',status='PROCESSING' WHERE taskId=?",GsonUtils.toJson(outline.getSections()),t.taskId());store.checkpoint(t,"Q_OUTLINE_WAIT","QUICK_OUTLINE");}
 @Transactional public void titles(RuntimeScope.Ticket t,java.util.List<ArticleState.TitleOption> titles){store.guard(t);jdbc.update("UPDATE article SET titleOptions=?,phase='TITLE_SELECTING',status='PROCESSING' WHERE taskId=?",GsonUtils.toJson(titles),t.taskId());store.checkpoint(t,"Q_TITLE_WAIT","QUICK_STAGE");}
 public String adviceFailure(String id){var rows=jdbc.queryForList("SELECT status,(updatedTime>=deadlineAt) expired FROM article_call WHERE taskId=? AND stepId='QUICK_ADVICE' ORDER BY createdTime DESC LIMIT 1",id);boolean timeout=!rows.isEmpty()&&"UNCERTAIN".equals(rows.getFirst().get("status"))&&(Boolean.TRUE.equals(rows.getFirst().get("expired"))||Integer.valueOf(1).equals(rows.getFirst().get("expired")));return timeout?"评审请求达到配置超时，未收到完整结果；图文保留。可单独重新评审，上次请求仍可能收费。":"评审请求未取得确定结果，图文保留；可单独重新评审，上次请求仍可能收费。";}
 public int imageCount(String id){var rows=jdbc.queryForList("SELECT requestJson FROM article_operation WHERE taskId=? AND action='QUICK_CREATE' AND JSON_EXTRACT(requestJson,'$.index') IS NOT NULL ORDER BY createdTime DESC LIMIT 1",id);if(rows.isEmpty())return 1;var value=GsonUtils.fromJson((String)rows.getFirst().get("requestJson"),QuickCreationController.ChooseTitle.class).imageCount();return value==null?1:Math.max(1,Math.min(5,value));}
 public boolean isQuick(String id){return jdbc.queryForObject("SELECT COUNT(*) FROM article_operation WHERE taskId=? AND action='QUICK_CREATE'",Integer.class,id)>0;}
 @Transactional public void text(RuntimeScope.Ticket t,String body){store.guard(t);jdbc.update("UPDATE article SET content=?,fullContent=?,phase='CONTENT_GENERATING' WHERE taskId=?",body,body,t.taskId());store.event(t.taskId(),"QUICK_TEXT",Map.of("content",body));}
 @Transactional public void stage(RuntimeScope.Ticket t,String phase,String body){store.guard(t);jdbc.update("UPDATE article SET mainTitle=COALESCE(mainTitle,topic),content=?,fullContent=?,phase=?,status='PROCESSING' WHERE taskId=?",body,body,phase,t.taskId());store.checkpoint(t,phase,"QUICK_STAGE");}
 @Transactional public void adviceStage(RuntimeScope.Ticket t){store.guard(t);jdbc.update("UPDATE article SET status='PROCESSING',phase='Q_ADVICE' WHERE taskId=?",t.taskId());store.checkpoint(t,"Q_ADVICE","QUICK_STAGE");}
 @Transactional public void done(RuntimeScope.Ticket t,ArticleState s,ReviewResult advice,String reason){store.guard(t);var trace=new ReviewTrace(1,"ADVISORY",0,0,reason,List.of(new ReviewTrace.DraftVersion(0,s.getContent(),advice)),advice);reviews.save(t.taskId(),trace);var saved=jdbc.queryForList("SELECT mediaJson FROM article_intervention WHERE taskId=?",t.taskId());var media=saved.isEmpty()?null:GsonUtils.fromJson((String)saved.getFirst().get("mediaJson"),MediaState.class);boolean missing=media==null||media.slots().size()<imageCount(t.taskId())||media.slots().stream().anyMatch(slot->!Set.of("SUCCESS","DEGRADED").contains(slot.status()));jdbc.update("UPDATE article SET status=?,phase='COMPLETED',completedTime=CURRENT_TIMESTAMP,errorMessage=? WHERE taskId=?",missing?"IMAGES_FAILED":"COMPLETED",missing?"配图未完成，正文已保留；请先核对调用结果，不自动重复生成":null,t.taskId());store.checkpoint(t,"DONE","ADVICE_READY");}
}
