package com.yupi.template.runtime;
import org.springframework.web.bind.annotation.*;import com.yupi.template.common.*;import com.yupi.template.model.dto.article.ArticleCreateRequest;import com.yupi.template.service.*;import java.util.*;import jakarta.servlet.http.HttpServletRequest;
@RestController @RequestMapping("/article/quick") @lombok.RequiredArgsConstructor public class QuickCreationController {
 @jakarta.annotation.Resource private com.yupi.template.modelconfig.ModelSettings models;
 @GetMapping("/text-models") public BaseResponse<?> textModels(HttpServletRequest r){users.getLoginUser(r);return ResultUtils.success(models.textChoices());}
 private final org.springframework.jdbc.core.JdbcTemplate jdbc;private final RuntimeStore runtime;
 private final RuntimeIntake intake;private final ArticleService articles;private final UserService users;private final QuickCreationStore quick;private final com.yupi.template.repository.ReviewTraceStore reviews;private final ArticleInterventionService interventions;
 @PostMapping public BaseResponse<String> create(@RequestBody ArticleCreateRequest request,HttpServletRequest r){if(request.getTopic()==null||request.getTopic().isBlank()||request.getTopic().length()>200)throw com.yupi.template.modelconfig.ModelSpec.bad("主题须为1–200字");if(request.getEnabledImageMethods()!=null&&(request.getEnabledImageMethods().size()!=1||!Set.of("DEMO","NANO_BANANA","DOUBAO").contains(request.getEnabledImageMethods().getFirst())))throw com.yupi.template.modelconfig.ModelSpec.bad("一键创作请选择一种配图方式");return ResultUtils.success(intake.quick(request,users.getLoginUser(r)));}
 public record RetryAdvice(String requestId,long expectedStateVersion,boolean acknowledgeCost){}
 @PostMapping("/{id}/advice-retry") @org.springframework.transaction.annotation.Transactional public BaseResponse<Boolean> retryAdvice(@PathVariable String id,@RequestBody RetryAdvice body,HttpServletRequest r){
  var user=users.getLoginUser(r);runtime.lock(id);articles.getArticleDetail(id,user);var a=articles.getByTaskId(id);
  if(!Objects.equals(a.getUserId(),user.getId())||!quick.isQuick(id)||body.requestId()==null||!body.requestId().matches("[A-Za-z0-9_-]{16,64}")||!body.acknowledgeCost())throw com.yupi.template.modelconfig.ModelSpec.bad("请确认评审可能收费");
  String json=com.yupi.template.utils.GsonUtils.toJson(body),hash=RuntimeExternal.hash(json);var old=jdbc.queryForList("SELECT payloadHash FROM article_operation WHERE taskId=? AND requestId=?",id,body.requestId());if(!old.isEmpty()){if(!hash.equals(old.getFirst().get("payloadHash")))throw com.yupi.template.modelconfig.ModelSpec.bad("重复请求内容不同");return ResultUtils.success(true);}
  var review=reviews.find(id);if(!Set.of("COMPLETED","IMAGES_FAILED").contains(a.getStatus())||review==null||review.review()!=null||RuntimeStore.number(runtime.runtime(id),"stateVersion")!=body.expectedStateVersion())throw com.yupi.template.modelconfig.ModelSpec.bad("当前状态不允许重试评审，请刷新");
  runtime.enqueue(id,body.requestId(),"QUICK_ADVICE_RETRY","Q_ADVICE",json);return ResultUtils.success(true);
 }
 public record RetryImage(String imageId,String prompt,String requestId,long expectedStateVersion,boolean acknowledgeCost){}
 @PostMapping("/{id}/image-retry") @org.springframework.transaction.annotation.Transactional public BaseResponse<Boolean> retryImage(@PathVariable String id,@RequestBody RetryImage body,HttpServletRequest r){
  var user=users.getLoginUser(r);runtime.lock(id);articles.getArticleDetail(id,user);var a=articles.getByTaskId(id);
  if(!Objects.equals(a.getUserId(),user.getId())||!quick.isQuick(id)||body.requestId()==null||!body.requestId().matches("[A-Za-z0-9_-]{16,64}")||body.prompt()!=null&&body.prompt().length()>4000)throw com.yupi.template.modelconfig.ModelSpec.bad("配图重试请求无效");
  String json=com.yupi.template.utils.GsonUtils.toJson(body),hash=RuntimeExternal.hash(json);var old=jdbc.queryForList("SELECT payloadHash FROM article_operation WHERE taskId=? AND requestId=?",id,body.requestId());if(!old.isEmpty()){if(!hash.equals(old.getFirst().get("payloadHash")))throw com.yupi.template.modelconfig.ModelSpec.bad("重复请求内容不同");return ResultUtils.success(true);}
  if(!Set.of("COMPLETED","IMAGES_FAILED").contains(a.getStatus())||RuntimeStore.number(runtime.runtime(id),"stateVersion")!=body.expectedStateVersion())throw com.yupi.template.modelconfig.ModelSpec.bad("状态已变化，请刷新后重试");
  var media=interventions.media(id);if(media==null)throw com.yupi.template.modelconfig.ModelSpec.bad("配图不存在");var slot=media.slots().stream().filter(x->x.id().equals(body.imageId())).findFirst().orElseThrow(()->com.yupi.template.modelconfig.ModelSpec.bad("配图不存在"));
  if(com.yupi.template.service.image.ImageProfile.paid(slot.requirement().getImageSource())&&!body.acknowledgeCost())throw com.yupi.template.modelconfig.ModelSpec.bad("请确认可能产生费用，未确认的旧请求也可能已收费");
  runtime.enqueue(id,body.requestId(),"QUICK_IMAGE_RETRY","MEDIA",json);return ResultUtils.success(true);
 }
 public record ChooseTitle(int index,String requestId,long expectedStateVersion,String textConfigId,Integer textConfigVersion,Integer imageCount){}
 @PostMapping("/{id}/title") @org.springframework.transaction.annotation.Transactional public BaseResponse<Boolean> title(@PathVariable String id,@RequestBody ChooseTitle body,HttpServletRequest r){
  var user=users.getLoginUser(r);runtime.lock(id);articles.getArticleDetail(id,user);var article=articles.getByTaskId(id);
  if(!Objects.equals(article.getUserId(),user.getId())||!quick.isQuick(id)||body.requestId()==null||!body.requestId().matches("[A-Za-z0-9_-]{16,64}"))throw com.yupi.template.modelconfig.ModelSpec.bad("标题确认请求无效");
  String json=com.yupi.template.utils.GsonUtils.toJson(body),hash=RuntimeExternal.hash(json);var old=jdbc.queryForList("SELECT payloadHash FROM article_operation WHERE taskId=? AND requestId=?",id,body.requestId());if(!old.isEmpty()){if(!hash.equals(old.getFirst().get("payloadHash")))throw com.yupi.template.modelconfig.ModelSpec.bad("重复确认内容发生变化");return ResultUtils.success(true);}
  if(RuntimeStore.number(runtime.runtime(id),"stateVersion")!=body.expectedStateVersion()||!"TITLE_SELECTING".equals(article.getPhase())||!"PROCESSING".equals(article.getStatus()))throw com.yupi.template.modelconfig.ModelSpec.bad("标题状态已变化，请刷新");
  var options=com.yupi.template.utils.GsonUtils.fromJson(article.getTitleOptions(),com.yupi.template.model.dto.article.ArticleState.TitleOption[].class);if(options==null||body.index()<0||body.index()>=options.length)throw com.yupi.template.modelconfig.ModelSpec.bad("请选择有效标题");if(body.imageCount()!=null&&(body.imageCount()<1||body.imageCount()>5))throw com.yupi.template.modelconfig.ModelSpec.bad("图片数量须为1至5");models.chooseTaskText(id,body.textConfigId(),body.textConfigVersion());var selected=options[body.index()];articles.confirmTitle(id,selected.getMainTitle(),selected.getSubTitle(),article.getUserDescription(),user);runtime.enqueue(id,body.requestId(),"QUICK_CREATE","Q_OUTLINE",json);return ResultUtils.success(true);
 }
 public record Confirm(java.util.List<com.yupi.template.model.dto.article.ArticleState.OutlineSection> outline,String requestId,long expectedStateVersion){}
 @PostMapping("/{id}/outline") @org.springframework.transaction.annotation.Transactional public BaseResponse<Boolean> confirm(@PathVariable String id,@RequestBody Confirm body,HttpServletRequest r){
  var user=users.getLoginUser(r);runtime.lock(id);articles.getArticleDetail(id,user);if(!Objects.equals(articles.getByTaskId(id).getUserId(),user.getId()))throw com.yupi.template.modelconfig.ModelSpec.bad("不能确认他人的文章");if(!quick.isQuick(id)||body.requestId()==null||!body.requestId().matches("[A-Za-z0-9_-]{16,64}"))throw com.yupi.template.modelconfig.ModelSpec.bad("确认请求无效");
  if(body.outline()==null||body.outline().isEmpty()||body.outline().size()>12||body.outline().stream().anyMatch(s->s.getTitle()==null||s.getTitle().isBlank()||s.getTitle().length()>200||s.getPoints()==null||s.getPoints().size()>12||s.getPoints().stream().anyMatch(p->p==null||p.length()>1000)))throw com.yupi.template.modelconfig.ModelSpec.bad("大纲格式无效");
  String json=com.yupi.template.utils.GsonUtils.toJson(body),hash=RuntimeExternal.hash(json);var old=jdbc.queryForList("SELECT payloadHash FROM article_operation WHERE taskId=? AND requestId=?",id,body.requestId());if(!old.isEmpty()){if(!hash.equals(old.getFirst().get("payloadHash")))throw com.yupi.template.modelconfig.ModelSpec.bad("重复确认内容发生变化");return ResultUtils.success(true);}
  if(RuntimeStore.number(runtime.runtime(id),"stateVersion")!=body.expectedStateVersion()||!"OUTLINE_EDITING".equals(articles.getByTaskId(id).getPhase())||!"PROCESSING".equals(articles.getByTaskId(id).getStatus()))throw com.yupi.template.modelconfig.ModelSpec.bad("大纲状态已变化，请刷新");
  articles.confirmOutline(id,body.outline(),user);runtime.enqueue(id,body.requestId(),"QUICK_CREATE","Q_BODY",json);return ResultUtils.success(true);
 }
 @GetMapping("/{id}") public BaseResponse<Map<String,Object>> get(@PathVariable String id,HttpServletRequest r){var article=articles.getArticleDetail(id,users.getLoginUser(r));Map<String,Object> out=new LinkedHashMap<>();out.put("quick",quick.isQuick(id));var run=runtime.runtime(id);out.put("stateVersion",run==null?0:run.get("stateVersion"));out.put("article",article);out.put("review",reviews.find(id));out.put("media",interventions.media(id));out.put("imageCount",quick.imageCount(id));if(quick.isQuick(id)){var text=models.taskText(id);out.put("textModel",Map.of("name",text.name(),"model",text.model()));}return ResultUtils.success(out);}
}
