package com.yupi.template.storage;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import java.nio.file.*;import java.io.*;import java.util.*;import java.util.zip.*;import com.yupi.template.controller.ArticleImageController;import com.yupi.template.service.*;import com.yupi.template.model.entity.User;import com.yupi.template.model.vo.ArticleVO;import org.springframework.beans.factory.ObjectProvider;import org.springframework.jdbc.core.JdbcTemplate;import jakarta.servlet.http.HttpServletRequest;
class A4ImageAccessTest {
 @TempDir Path root;
 @Test void zipContainsOnlyOwnedLocalImagesAndEscapesHtml()throws Exception{
  var store=new LocalImageStorage(root.toString(),10000);String url=store.save(com.yupi.template.model.dto.image.ImageData.fromBytes(A4StorageTest.png(),"image/png"),"x");var users=mock(UserService.class);var articles=mock(ArticleService.class);var request=mock(HttpServletRequest.class);var user=new User();user.setId(1L);when(users.getLoginUser(request)).thenReturn(user);var article=new ArticleVO();article.setMainTitle("<script>bad</script>");article.setFullContent("body ![x]("+url+")");var item=new ArticleVO.ImageItem();item.setUrl(url);article.setImages(List.of(item));when(articles.getArticleDetail("task",user)).thenReturn(article);ObjectProvider<LocalImageStorage> provider=mock(ObjectProvider.class);when(provider.getIfAvailable()).thenReturn(store);var controller=new ArticleImageController(provider,users,articles,mock(JdbcTemplate.class));var response=controller.export("task",request);var files=new HashMap<String,byte[]>();try(var in=new ZipInputStream(new ByteArrayInputStream(response.getBody()))){for(ZipEntry e;(e=in.getNextEntry())!=null;)files.put(e.getName(),in.readAllBytes());}assertEquals(4,files.size());assertTrue(new String(files.get("article.md")).contains("images/"));assertFalse(new String(files.get("article.md")).contains("/api/images/"));assertFalse(new String(files.get("index.html")).contains("<script>"));assertTrue(files.keySet().stream().noneMatch(x->x.contains("..")));
 }
 @Test void unownedImageRejectedBeforeDisk(){var users=mock(UserService.class);var user=new User();user.setId(2L);when(users.getLoginUser(any())).thenReturn(user);ObjectProvider<LocalImageStorage> provider=mock(ObjectProvider.class);var controller=new ArticleImageController(provider,users,mock(ArticleService.class),mock(JdbcTemplate.class));assertThrows(com.yupi.template.exception.BusinessException.class,()->controller.image("a".repeat(32),mock(HttpServletRequest.class)));verifyNoInteractions(provider);}
 @Test void unauthenticatedExportRejected(){var users=mock(UserService.class);when(users.getLoginUser(any())).thenThrow(new com.yupi.template.exception.BusinessException(com.yupi.template.exception.ErrorCode.NOT_LOGIN_ERROR));ObjectProvider<LocalImageStorage> provider=mock(ObjectProvider.class);var controller=new ArticleImageController(provider,users,mock(ArticleService.class),mock(JdbcTemplate.class));assertThrows(com.yupi.template.exception.BusinessException.class,()->controller.export("task",mock(HttpServletRequest.class)));verifyNoInteractions(provider);}
}
