package com.yupi.template.storage;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import java.nio.file.*;import java.io.*;import java.util.*;import javax.imageio.ImageIO;import java.awt.image.BufferedImage;
import com.yupi.template.model.dto.image.*;import com.yupi.template.service.*;import com.yupi.template.model.enums.ImageMethodEnum;import com.yupi.template.runtime.*;import org.springframework.test.util.ReflectionTestUtils;
class A4StorageTest {
 @TempDir Path dir;
 static byte[] png()throws Exception{var out=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(4,4,BufferedImage.TYPE_INT_RGB),"png",out);return out.toByteArray();}
 @Test void runtimeRecordsStorageFailureSeparately(){var ledger=mock(RuntimeLedger.class);var store=mock(RuntimeStore.class);var ticket=new RuntimeScope.Ticket("task","request","run",1);when(ledger.prepare(any(),any(),any(),any())).thenReturn(new RuntimeLedger.Call("a".repeat(64),true,"IN_FLIGHT",null,null,System.currentTimeMillis()+10000));var external=new RuntimeExternal(ledger,store,List.of());assertThrows(ImageStorageException.class,()->external.call(ticket,"IMAGE:1","image:NANO_BANANA","{}",()->{throw new ImageStorageException();}));verify(ledger).storageFailed(ticket,"a".repeat(64));verify(ledger,never()).uncertain(any(),any());}
 @Test void roundTripAndRestart()throws Exception{var s=new LocalImageStorage(dir.toString(),10000);String url=s.save(ImageData.fromBytes(png(),"image/png"),"../../ignored");assertTrue(ImageReferences.local(url));assertArrayEquals(s.read(url.substring(12)),new LocalImageStorage(dir.toString(),10000).read(url.substring(12)));assertFalse(url.contains(dir.toString()));}
 @Test void objectsNeverOverwrite()throws Exception{var s=new LocalImageStorage(dir.toString(),10000);assertNotEquals(s.save(ImageData.fromBytes(png(),"image/png"),"x"),s.save(ImageData.fromBytes(png(),"image/png"),"x"));}
 @Test void traversalRejected(){var s=new LocalImageStorage(dir.toString(),10000);for(String id:List.of("../secret","..%2fsecret","/etc/passwd","a.png",""))assertThrows(ImageStorageException.class,()->s.read(id));}
 @Test void activeSvgRejected(){var s=new LocalImageStorage(dir.toString(),10000);assertThrows(ImageStorageException.class,()->s.save(ImageData.fromBytes("<svg onload='alert(1)'/>".getBytes(),"image/svg+xml"),"x"));}
 @Test void invalidAndOversizedRejected()throws Exception{var s=new LocalImageStorage(dir.toString(),10);assertThrows(ImageStorageException.class,()->s.save(ImageData.fromBytes(png(),"image/png"),"x"));assertThrows(ImageStorageException.class,()->new LocalImageStorage(dir.toString(),10000).save(ImageData.fromBytes("not an image".getBytes(),"image/png"),"x"));}
 @Test void blockedLocalFetch(){var s=new LocalImageStorage(dir.toString(),10000);assertThrows(ImageStorageException.class,()->s.save(ImageData.fromUrl("https://127.0.0.1/private"),"x"));}
 @Test void dangerousReferencesRejected(){for(String s:List.of("javascript:alert(1)","data:image/svg+xml,x","file:///etc/passwd","//evil/x","/api/images/../secret"))assertFalse(ImageReferences.allowed(s));assertTrue(ImageReferences.allowed("https://old.example/cos.png"));assertTrue(ImageReferences.local("/api/images/"+"a".repeat(32)));}
 @Test void missingModelResultDoesNotBecomeStorageFailure(){var strategy=new ImageServiceStrategy();var model=mock(ImageSearchService.class);when(model.getMethod()).thenReturn(ImageMethodEnum.NANO_BANANA);when(model.isAvailable()).thenReturn(true);var storage=mock(ImageStorage.class);ReflectionTestUtils.setField(strategy,"imageSearchServices",List.of(model));ReflectionTestUtils.setField(strategy,"generated",mock(GeneratedImageStore.class));ReflectionTestUtils.setField(strategy,"imageStorage",storage);strategy.init();assertEquals("EXTERNAL_UNCERTAIN",assertThrows(RuntimeStop.class,()->strategy.getImageAndUpload("NANO_BANANA",ImageRequest.builder().prompt("one image").build())).status);verifyNoInteractions(storage);}
 @Test void failedSaveReusesGeneratedBytes()throws Exception{
  var strategy=new ImageServiceStrategy();var model=mock(ImageSearchService.class);when(model.getMethod()).thenReturn(ImageMethodEnum.NANO_BANANA);when(model.isAvailable()).thenReturn(true);var data=ImageData.fromBytes(png(),"image/png");when(model.getImageData(any())).thenReturn(data);
  var generated=mock(GeneratedImageStore.class);when(generated.key(any())).thenReturn("key");when(generated.find("key")).thenReturn(null,data);var storage=mock(ImageStorage.class);when(storage.save(any(),any())).thenThrow(new ImageStorageException()).thenReturn("/api/images/"+"a".repeat(32));
  ReflectionTestUtils.setField(strategy,"imageSearchServices",List.of(model));ReflectionTestUtils.setField(strategy,"generated",generated);ReflectionTestUtils.setField(strategy,"imageStorage",storage);strategy.init();var request=ImageRequest.builder().prompt("one image").position(1).build();assertThrows(ImageStorageException.class,()->strategy.getImageAndUpload("NANO_BANANA",request));assertTrue(strategy.getImageAndUpload("NANO_BANANA",request).isSuccess());verify(model,times(1)).getImageData(any());verify(generated).save("key",data);
 }
}
