package com.yupi.template.modelconfig;
import org.springframework.ai.chat.model.*;import org.springframework.ai.chat.messages.AssistantMessage;import org.springframework.ai.chat.prompt.Prompt;import org.springframework.stereotype.Component;import com.google.gson.*;import java.util.*;import reactor.core.publisher.Flux;
@Component @org.springframework.context.annotation.Primary @lombok.RequiredArgsConstructor
public class ManagedChatModel implements ChatModel {
 private final ModelSettings settings;private final SafeModelHttp http;
 public record TextResult(String text,String requestId,Map<String,Long> usage){}
 private ModelSpec current(){String task=ModelContext.task();if(task==null)throw ModelSpec.bad("缺少任务配置上下文，拒绝使用可变默认模型");return settings.taskText(task);}
 public ChatResponse call(Prompt prompt){ModelSpec s=current();return response(complete(s,settings.key(s),prompt.getContents(),s.maxOutputTokens()).text());}
 private static ChatResponse response(String text){return new ChatResponse(List.of(new Generation(new AssistantMessage(text))));}
 private static String url(ModelSpec s){return s.endpoint()+("dashscope".equals(s.protocol())?"/api/v1/services/aigc/text-generation/generation":"/chat/completions");}
 private static String body(ModelSpec s,String prompt,int limit,boolean stream){var messages=List.of(Map.of("role","user","content",prompt));Map<String,Object> b=new LinkedHashMap<>();b.put("model",s.model());if("dashscope".equals(s.protocol())){b.put("input",Map.of("messages",messages));b.put("parameters",Map.of("result_format","message","max_tokens",limit,"incremental_output",true));}else{b.put("messages",messages);b.put("max_tokens",limit);b.put("stream",stream);}return new Gson().toJson(b);}
 public static class Failure extends RuntimeException {public final String requestId;public final boolean uncertain;Failure(String message,String id,boolean uncertain){super(message);this.requestId=id;this.uncertain=uncertain;}}
 private static void status(int code){status(code,"");}
 private static void status(int code,String id){if(code==401||code==403)throw new Failure("MODEL_AUTH：鉴权失败",id,false);if(code==429)throw new Failure("MODEL_QUOTA：额度或限流",id,false);if(code!=200)throw new Failure("MODEL_RESPONSE：请求失败，未自动重试",id,code>=500||code==408);}
 public TextResult completeReview(ModelSpec s,String key,String prompt,int limit){return completeRequest(s,key,prompt,limit,true);}
 public TextResult complete(ModelSpec s,String key,String prompt,int limit){return completeRequest(s,key,prompt,limit,false);}
 static String reviewBody(ModelSpec s,String prompt,int limit){var json=JsonParser.parseString(body(s,prompt,limit,false)).getAsJsonObject();String host=java.net.URI.create(s.endpoint()).getHost();if("compatible".equals(s.protocol())&&s.model().startsWith("deepseek-v4-")&&Set.of("ark.cn-beijing.volces.com","api.deepseek.com").contains(host))json.add("thinking",new Gson().toJsonTree(Map.of("type","disabled")));return json.toString();}
 private TextResult completeRequest(ModelSpec s,String key,String prompt,int limit,boolean review){var r=http.post(url(s),"Authorization","Bearer "+key,review?reviewBody(s,prompt,limit):body(s,prompt,limit,false),Math.min(s.timeoutSeconds(),180));status(r.status(),r.requestId());try{var root=JsonParser.parseString(r.body()).getAsJsonObject();String text=content(s,root,false);Map<String,Long> usage=new TreeMap<>();if(root.has("usage"))for(var e:root.getAsJsonObject("usage").entrySet())if(e.getKey().matches("[a-z_]{1,60}")&&e.getValue().isJsonPrimitive()&&e.getValue().getAsJsonPrimitive().isNumber())usage.put(e.getKey(),e.getValue().getAsLong());if(text.isBlank())throw new Exception();return new TextResult(text,r.requestId(),usage);}catch(Exception e){throw ModelSpec.bad("MODEL_INVALID_RESPONSE：无有效文字，未重试");}}
 private static String content(ModelSpec s,JsonObject root,boolean stream){if("dashscope".equals(s.protocol()))root=root.getAsJsonObject("output");if(root==null||!root.has("choices")||root.getAsJsonArray("choices").isEmpty())return "";var choice=root.getAsJsonArray("choices").get(0).getAsJsonObject();var m=choice.getAsJsonObject(stream&&!"dashscope".equals(s.protocol())?"delta":"message");return m==null||!m.has("content")||m.get("content").isJsonNull()?"":m.get("content").getAsString();}
 public Flux<ChatResponse> stream(Prompt prompt){ModelSpec s=current();String key=settings.key(s),text=prompt.getContents();return Flux.create(sink->{var call=http.call(url(s),"Authorization","Bearer "+key,body(s,text,s.maxOutputTokens(),true),s.timeoutSeconds(),true);sink.onCancel(call::cancel);call.enqueue(new okhttp3.Callback(){public void onFailure(okhttp3.Call c,java.io.IOException e){if(!sink.isCancelled())sink.error(ModelSpec.bad("MODEL_TRANSPORT_UNCERTAIN：未重试"));}public void onResponse(okhttp3.Call c,okhttp3.Response r){try(r){status(r.code());var in=r.body().source();long count=0;while(!sink.isCancelled()&&!in.exhausted()){String line=in.readUtf8LineStrict(262144);count+=line.length();if(count>1048576)throw new Exception();if(!line.startsWith("data:"))continue;String data=line.substring(5).trim();if(data.equals("[DONE]"))break;String part=content(s,JsonParser.parseString(data).getAsJsonObject(),true);if(!part.isEmpty())sink.next(response(part));}if(!sink.isCancelled())sink.complete();}catch(Exception e){if(!sink.isCancelled())sink.error(ModelSpec.bad("MODEL_STREAM_UNCERTAIN：流中断，未重试"));}}});});}
}
