package com.yupi.template.modelconfig;
import org.springframework.web.bind.annotation.*;import com.yupi.template.annotation.AuthCheck;import com.yupi.template.common.*;import jakarta.servlet.http.HttpServletRequest;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.support.TransactionTemplate;import com.yupi.template.utils.GsonUtils;
@RestController @RequestMapping("/admin/models") @lombok.RequiredArgsConstructor
public class ModelAdminController {
 private final ModelSettings settings;private final com.yupi.template.service.UserService users;private final JdbcTemplate jdbc;private final org.springframework.transaction.PlatformTransactionManager tx;private final ManagedChatModel text;private final SafeModelHttp http;private final com.yupi.template.storage.LocalImageStorage storage;
 private long admin(HttpServletRequest r){var user=users.getLoginUser(r);if(!"admin".equals(user.getUserRole()))throw new com.yupi.template.exception.BusinessException(com.yupi.template.exception.ErrorCode.NO_AUTH_ERROR);return user.getId();}
 @GetMapping @AuthCheck(mustRole="admin") public BaseResponse<Map<String,Object>> list(HttpServletRequest r){admin(r);var session=r.getSession();String token; synchronized(session){token=(String)session.getAttribute("model-csrf");if(token==null){token=UUID.randomUUID().toString();session.setAttribute("model-csrf",token);}}return ResultUtils.success(Map.of("items",settings.list(),"csrf",token,"realCallsVerified",false));}
 @PostMapping("/validate") @AuthCheck(mustRole="admin") public BaseResponse<Map<String,Object>> validate(@RequestBody ModelSpec spec,HttpServletRequest r){admin(r);return ResultUtils.success(Map.of("spec",spec.normalized(),"message","仅格式有效；未联网，不代表Key、模型或账户可用"));}
 @PostMapping("/save") @AuthCheck(mustRole="admin") public BaseResponse<String> save(@RequestBody ModelSettings.Save input,HttpServletRequest r){return ResultUtils.success(settings.save(input,admin(r)));}
 public record Probe(String id,int version,String requestId,boolean consent){}
 @PostMapping("/test") @AuthCheck(mustRole="admin") public BaseResponse<Map<String,Object>> test(@RequestBody Probe input,HttpServletRequest r){
  long actor=admin(r);if(!input.consent()||input.requestId()==null||!input.requestId().matches("[a-f0-9-]{36}"))throw ModelSpec.bad("实际测试可能收费，必须明确确认");
  ModelSpec s=settings.get(input.id(),input.version());if("demo".equals(s.protocol()))return ResultUtils.success(Map.of("status","FORMAT_ONLY","message","演示模式不连接模型"));
  boolean fresh=Boolean.TRUE.equals(new TransactionTemplate(tx).execute(status->{jdbc.queryForList("SELECT id FROM user WHERE id=? FOR UPDATE",actor);var old=jdbc.queryForList("SELECT actor,configId,version FROM model_probe WHERE requestId=?",input.requestId());if(!old.isEmpty()){var row=old.getFirst();if(((Number)row.get("actor")).longValue()!=actor||!s.id().equals(row.get("configId"))||s.version()!=((Number)row.get("version")).intValue())throw ModelSpec.bad("测试请求冲突");return false;}int count=jdbc.queryForObject("SELECT COUNT(*) FROM model_probe WHERE actor=? AND createdAt>DATE_SUB(NOW(),INTERVAL 1 DAY)",Integer.class,actor);if(count>=5)throw ModelSpec.bad("每日最多5次实际测试，请查看已有结果");jdbc.update("INSERT INTO model_probe(requestId,actor,configId,version,status) VALUES (?,?,?,?,?)",input.requestId(),actor,s.id(),s.version(),"SUBMITTED");jdbc.update("INSERT INTO model_audit(actor,action,configId,version) VALUES (?,?,?,?)",actor,"PAID_TEST_CONSENT",s.id(),s.version());return true;}));
  if(!fresh){var row=jdbc.queryForMap("SELECT status,result FROM model_probe WHERE requestId=?",input.requestId());return ResultUtils.success(Map.of("status",row.get("status"),"message","重复请求未再次调用；SUBMITTED表示结果未确认，请勿盲目重试"));}
  Map<String,Object> result=new LinkedHashMap<>();result.put("status","SUCCEEDED");result.put("requestId","");try{
   String key=settings.key(s);if("TEXT".equals(s.kind())){var out=text.complete(s,key,"Reply with OK only.",16);result.put("requestId",out.requestId());result.put("usage",out.usage());result.put("message","收到有效文字；输出不回显");}
   else{var profile=new com.yupi.template.service.image.ImageProfile(s.protocol(),s.model(),s.endpoint(),s.imageSize(),s.aspectRatio(),Math.min(2048,s.maxOutputTokens()),Math.min(60,s.timeoutSeconds()),null,s.id(),s.version());var adapter=new com.yupi.template.service.image.ImageHttpTransport(){@Override public Response post(String u,String h,String k,String j,int t){return http.post(u,h,k,j,t);}};var data=com.yupi.template.service.image.ImageProviderProtocol.generate(adapter,profile,key,"A single blue circle on a white background. No text.");var metadata=data.getMetadata();if(metadata!=null){result.put("requestId",Objects.toString(metadata.requestId(),""));result.put("usage",metadata.usage());}result.put("image",storage.save(data,"model-test"));result.put("message","生成1张测试图片并保存本地；请创建文章验证完整流程");}
  }catch(com.yupi.template.storage.ImageStorageException e){result.put("status","STORAGE_FAILED");result.put("message","图片可能已收费生成，本地保存失败；未重试");}
  catch(com.yupi.template.service.image.ImageProviderException e){result.put("status",e.uncertain()?"UNCERTAIN":"REJECTED");result.put("message",e.getMessage());result.put("requestId",Objects.toString(e.requestId(),""));}
  catch(ManagedChatModel.Failure e){result.put("status",e.uncertain?"UNCERTAIN":"REJECTED");result.put("message",e.getMessage());result.put("requestId",e.requestId);}
  catch(Exception e){result.put("status","UNCERTAIN");result.put("message","调用失败或结果不确定；检查配置或供应商账单，未重试");}
  jdbc.update("UPDATE model_probe SET status=?,result=? WHERE requestId=?",result.get("status"),GsonUtils.toJson(result),input.requestId());result.remove("image");return ResultUtils.success(result);
 }
}
