package com.yupi.template.modelconfig;
import org.springframework.stereotype.Service;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.annotation.Transactional;import org.springframework.core.env.Environment;import com.yupi.template.utils.GsonUtils;import java.util.*;
@Service @lombok.RequiredArgsConstructor
public class ModelSettings {
 private final JdbcTemplate jdbc;private final ModelVault vault;private final Environment env;
 public record Save(ModelSpec spec,String apiKey,boolean clearKey,boolean enabled,boolean makeDefault) { public String toString(){return "ModelSettings.Save[redacted]";} }
 public List<Map<String,Object>> list(){var rows=jdbc.queryForList("SELECT id,version,kind,spec,(secret IS NOT NULL) AS configured,enabled,deleted FROM model_config ORDER BY kind,id");var defaults=jdbc.queryForList("SELECT configId FROM model_default");Set<String> ids=new HashSet<>();defaults.forEach(r->ids.add((String)r.get("configId")));return rows.stream().map(r->{Map<String,Object> result=new LinkedHashMap<>();result.put("spec",GsonUtils.fromJson((String)r.get("spec"),ModelSpec.class));result.put("configured",((Number)r.get("configured")).intValue()!=0);result.put("enabled",r.get("enabled"));result.put("deleted",r.get("deleted"));result.put("isDefault",ids.contains(r.get("id")));return result;}).toList();}
 @Transactional public String save(Save input,long actor){
  if(input==null||input.spec()==null)throw ModelSpec.bad("缺少配置");ModelSpec supplied=input.spec().normalized();String id=supplied.id();boolean fresh=id==null||id.isBlank();if(fresh)id=UUID.randomUUID().toString().replace("-","");if(!id.matches("[a-f0-9]{32}"))throw ModelSpec.bad("配置ID无效");
  int version=1;String encrypted=null;
  if(!fresh){var rows=jdbc.queryForList("SELECT * FROM model_config WHERE id=? FOR UPDATE",id);if(rows.isEmpty())throw ModelSpec.bad("配置不存在");var row=rows.getFirst();version=((Number)row.get("version")).intValue()+1;if(supplied.version()!=version-1)throw ModelSpec.bad("配置版本冲突，请刷新");ModelSpec old=GsonUtils.fromJson((String)row.get("spec"),ModelSpec.class);if(!old.kind().equals(supplied.kind())||!old.protocol().equals(supplied.protocol())||!old.endpoint().equals(supplied.endpoint()))throw ModelSpec.bad("协议和地址不可改写；请新建配置，保护在途任务");encrypted=(String)row.get("secret");}
  if(input.clearKey()&&input.apiKey()!=null&&!input.apiKey().isBlank())throw ModelSpec.bad("清除Key与提交新Key不能同时选择");
  if(input.clearKey())encrypted=null;else if(input.apiKey()!=null&&!input.apiKey().isBlank()){if(input.apiKey().length()>4096||!input.apiKey().matches("[!-~]+"))throw ModelSpec.bad("Key格式无效");encrypted=vault.encrypt(id,input.apiKey());}
  ModelSpec spec=new ModelSpec(id,version,supplied.name(),supplied.kind(),supplied.protocol(),supplied.endpoint(),supplied.model(),supplied.timeoutSeconds(),supplied.maxOutputTokens(),supplied.imageSize(),supplied.aspectRatio());
  if(input.enabled()&&!"demo".equals(spec.protocol())&&encrypted==null)throw ModelSpec.bad("启用真实模型前请配置Key");
  if(fresh)jdbc.update("INSERT INTO model_config(id,version,kind,spec,secret,enabled) VALUES (?,?,?,?,?,?)",id,version,spec.kind(),GsonUtils.toJson(spec),encrypted,input.enabled());else jdbc.update("UPDATE model_config SET version=?,spec=?,secret=?,enabled=? WHERE id=?",version,GsonUtils.toJson(spec),encrypted,input.enabled(),id);
  jdbc.update("INSERT INTO model_version(configId,version,spec) VALUES (?,?,?)",id,version,GsonUtils.toJson(spec));
  if(input.makeDefault()){if(!input.enabled())throw ModelSpec.bad("默认配置必须启用");jdbc.update("INSERT INTO model_default(kind,configId) VALUES (?,?) ON DUPLICATE KEY UPDATE configId=VALUES(configId)",spec.kind(),id);}
  jdbc.update("INSERT INTO model_audit(actor,action,configId,version) VALUES (?,?,?,?)",actor,input.clearKey()?"KEY_CLEAR":"SAVE",id,version);return id;
 }
 public ModelSpec get(String id,int version){var rows=jdbc.queryForList("SELECT spec FROM model_version WHERE configId=? AND version=?",id,version);if(rows.isEmpty())throw ModelSpec.bad("配置版本不存在");return GsonUtils.fromJson((String)rows.getFirst().get("spec"),ModelSpec.class);}
 public String key(ModelSpec spec){if(spec.id().startsWith("env:")){String key=env.getProperty(spec.id().substring(4),"");if(key.isBlank())throw ModelSpec.bad("尚未配置文字模型，请管理员进入模型设置");return key;}var rows=jdbc.queryForList("SELECT secret FROM model_config WHERE id=?",spec.id());if(rows.isEmpty())throw ModelSpec.bad("任务原配置丢失，请恢复备份");return vault.decrypt(spec.id(),(String)rows.getFirst().get("secret"));}
 public ModelSpec selection(String kind,String protocol){
  var defaults=jdbc.queryForList("SELECT c.spec,c.enabled FROM model_default d JOIN model_config c ON c.id=d.configId WHERE d.kind=?",kind);
  if(!defaults.isEmpty()){var row=defaults.getFirst();ModelSpec s=GsonUtils.fromJson((String)row.get("spec"),ModelSpec.class);if(protocol==null||protocol.equals(s.protocol())){if(!Boolean.TRUE.equals(row.get("enabled"))&&!Integer.valueOf(1).equals(row.get("enabled")))throw ModelSpec.bad("默认模型已停用，请管理员选择有效配置");return s;}}
  if(protocol!=null){var rows=jdbc.queryForList("SELECT spec FROM model_config WHERE kind=? AND enabled=TRUE AND deleted=FALSE ORDER BY id",kind);for(var row:rows){ModelSpec s=GsonUtils.fromJson((String)row.get("spec"),ModelSpec.class);if(protocol.equals(s.protocol()))return s;}}
  if("TEXT".equals(kind))return new ModelSpec("env:DASHSCOPE_API_KEY",0,"环境兼容","TEXT","dashscope",SafeModelHttp.base(env.getProperty("TEXT_MODEL_BASE_URL","https://dashscope.aliyuncs.com"),"dashscope"),env.getProperty("TEXT_MODEL","qwen-plus"),60,env.getProperty("TEXT_MAX_TOKENS",Integer.class,2000),"1K","1:1");return null;
 }
 public void snapshot(String taskId){ModelSpec s=selection("TEXT",null);key(s);jdbc.update("INSERT INTO article_text_profile(taskId,spec) VALUES (?,?)",taskId,GsonUtils.toJson(s));}
 public ModelSpec taskText(String taskId){if(taskId==null)return selection("TEXT",null);var rows=jdbc.queryForList("SELECT spec FROM article_text_profile WHERE taskId=?",taskId);if(rows.isEmpty())throw ModelSpec.bad("旧任务没有文字配置快照，请新建任务；原草稿仍保留");return GsonUtils.fromJson((String)rows.getFirst().get("spec"),ModelSpec.class);}
 public List<Map<String,Object>> textChoices(){return jdbc.queryForList("SELECT spec FROM model_config WHERE kind='TEXT' AND enabled=TRUE AND deleted=FALSE AND secret IS NOT NULL ORDER BY id").stream().map(r->{var s=GsonUtils.fromJson((String)r.get("spec"),ModelSpec.class);return Map.<String,Object>of("id",s.id(),"version",s.version(),"name",s.name(),"model",s.model());}).toList();}
 public void chooseTaskText(String taskId,String id,Integer version){if(id==null||id.isBlank())return;var rows=jdbc.queryForList("SELECT spec FROM model_config WHERE id=? AND kind='TEXT' AND enabled=TRUE AND deleted=FALSE AND secret IS NOT NULL",id);if(rows.isEmpty())throw ModelSpec.bad("文字模型已停用或未配置，请刷新选择");var s=GsonUtils.fromJson((String)rows.getFirst().get("spec"),ModelSpec.class);if(version==null||s.version()!=version)throw ModelSpec.bad("文字模型配置已变化，请刷新");if(jdbc.update("UPDATE article_text_profile SET spec=? WHERE taskId=?",GsonUtils.toJson(s),taskId)!=1)throw ModelSpec.bad("任务文字配置快照不存在");}
 public String defaultImage(){var s=selection("IMAGE",null);if(s==null)return "DEMO";return switch(s.protocol()){case "gemini"->"NANO_BANANA";case "doubao"->"DOUBAO";default->"DEMO";};}
}
