import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const info=JSON.parse(readFileSync(process.argv[2],'utf8'));
const stamp=new Date().toISOString().replace(/[:.]/g,'-');
const fixturePrefix='browser-'+stamp.toLowerCase();
const out=resolve(info.out,'browser-'+stamp);mkdirSync(out,{recursive:true});
const profile=resolve(info.work,'chrome-profile-'+stamp);mkdirSync(profile,{recursive:true});
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','--disable-extensions','about:blank'],{windowsHide:true,stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let ws,sessionId,seq=0;const pending=new Map(),events=[],network=[],errors=[],checks=[],cases=[];
function send(method,params={},session=sessionId){return new Promise((ok,no)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);no(Error('CDP timeout '+method))},30000);pending.set(id,{ok,no,timer});ws.send(JSON.stringify({id,method,params,...(session?{sessionId:session}:{})}));})}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
async function wait(expression,label,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression)){checks.push(label);return;}await sleep(150)}throw Error('UI timeout '+label+' '+await evaluate('document.body.innerText.slice(-2000)'))}
const textHas=s=>`document.body.innerText.includes(${JSON.stringify(s)})`;
async function clickText(s){const clicked=await evaluate(`(()=>{const x=[...document.querySelectorAll('button')].find(x=>x.innerText.replace(/\\s/g,'').includes(${JSON.stringify(s.replace(/\s/g,''))}));if(!x||x.disabled)return false;x.click();return true})()`);if(!clicked)throw Error('Button missing '+s)}
async function input(selector,value){await evaluate(`(()=>{const x=document.querySelector(${JSON.stringify(selector)});if(!x)throw Error('input missing');x.value=${JSON.stringify(value)};x.dispatchEvent(new Event('input',{bubbles:true}));x.dispatchEvent(new Event('change',{bubbles:true}))})()`)}
async function screenshot(name){if(await evaluate('location.pathname.startsWith("/article/")')){const snapshot=await evaluate('(async()=>{const p=location.pathname;return {article:await (await fetch("/api"+p)).json(),intervention:await (await fetch("/api"+p+"/interventions")).json()}})()');cases.push({name,...snapshot});}
await sleep(350);const p=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(resolve(out,name+'.png'),Buffer.from(p.data,'base64'))}
async function navigate(path){path=path.replace('/article/browser-','/article/'+fixturePrefix+'-');await send('Page.navigate',{url:info.frontend+path});await wait('document.readyState === "complete"','loaded '+path,120000)}
try{
 const ready=JSON.parse(readFileSync(resolve(info.work,'target/a2-http-ready.json'),'utf8'));if(ready.failedTests.length)throw Error('HTTP tests failed: '+ready.failedTests);
 let sql='USE ai_passage_creator;';for(const kind of ['human','edit','long','old']){const id=fixturePrefix+'-'+kind;sql+=`INSERT INTO article(taskId,userId,topic,mainTitle,subTitle,outline,content,fullContent,status,phase,userDescription,enabledImageMethods) SELECT '${id}',userId,topic,'A2 ${id}',subTitle,outline,content,fullContent,status,phase,userDescription,enabledImageMethods FROM article WHERE taskId='browser-${kind}';INSERT INTO article_review(taskId,reviewJson) SELECT '${id}',reviewJson FROM article_review WHERE taskId='browser-${kind}';`}
 const seed=spawnSync('docker',['exec','-i',info.prefix+'-mysql','mysql','-uroot','-pa2-test-only'],{input:sql,encoding:'utf8',windowsHide:true});if(seed.status!==0)throw Error('Fixture clone failed '+seed.stderr);

 for(let i=0;i<120&&!existsSync(resolve(profile,'DevToolsActivePort'));i++)await sleep(250);
 const [port,path]=readFileSync(resolve(profile,'DevToolsActivePort'),'utf8').trim().split(/\r?\n/);
 ws=new WebSocket('ws://127.0.0.1:'+port+path);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.no(Error(JSON.stringify(m.error))):p.ok(m.result)}return}events.push(m);if(m.method==='Runtime.exceptionThrown')errors.push(m.params);if(m.method==='Runtime.consoleAPICalled'&&['error','warning'].includes(m.params.type))errors.push({type:m.params.type,args:m.params.args.map(x=>x.value||x.description)});if(m.method==='Network.responseReceived')network.push({url:m.params.response.url,status:m.params.response.status,type:m.params.type});if(m.method==='Network.loadingFailed')network.push({requestId:m.params.requestId,error:m.params.errorText,canceled:m.params.canceled})};
 const target=await send('Target.createTarget',{url:'about:blank'},null);sessionId=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true},null)).sessionId;
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await navigate('/user/login');await wait('!!document.querySelector("input[placeholder=请输入账号]")','login form');await input('input[placeholder=请输入账号]','a2owner');await input('input[placeholder=请输入密码]','a2-local-only');await clickText('登录');await wait('!location.pathname.includes("/user/login")','real backend login');
 await navigate('/article/browser-human');await wait(textHas('待人工处理'),'review panel');await screenshot('01-desktop-review');
 await clickText('人工接受并继续配图');await wait(textHas('我理解事实尚未核查'),'accept dialog');await screenshot('02-human-accept');await evaluate('document.querySelector(".ant-modal input[type=checkbox]").click()');await clickText('确认接受并继续配图');await wait(textHas('配图待重试'),'accept continues real backend');await wait(textHas('降级 / 占位'),'fallback labeled');await evaluate('document.querySelector(".media-section").scrollIntoView({block:"center"})');await screenshot('03-media-failure');
 await clickText('重试 image-1');await wait(textHas('图文任务完成'),'one image retry completes');await evaluate('document.querySelector(".media-section").scrollIntoView({block:"center"})');await screenshot('04-human-complete');
 await send('Page.reload');await wait(textHas('人工决定（原评审保留）'),'human decision survives refresh');await wait(textHas('固定评审问题'),'original issues preserved');
 await navigate('/article/browser-edit');await wait(textHas('待人工处理'),'edit target');await clickText('编辑后重新评审');await wait('!!document.querySelector("textarea[aria-label=编辑正文]")','editor');await input('textarea[aria-label=编辑正文]','## 开始行动\n\nREVISE_ME 请解释得更清楚。\n\n保留这一段，不要重写。');await clickText('保存新版本并评审');await wait(textHas('评审中'),'reviewing state');await screenshot('05-reviewing');await wait(textHas('局部修订中'),'revising state');await screenshot('06-revising');await wait(textHas('文本评审通过'),'text passed');await wait(textHas('配图待重试'),'edit media terminal');await evaluate('document.querySelector(".version-tools button[role=switch]").click()');await screenshot('07-version-diff');await send('Page.reload');await wait(textHas('全局版本 v2'),'versions restored');
 await navigate('/article/browser-old');await wait(textHas('这篇文章暂无评审记录'),'old article compatible');await screenshot('08-old-article');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await navigate('/article/browser-long');await wait(textHas('全局版本 v1'),'mobile long article');await screenshot('09-mobile-review');
 const overflow=await evaluate('({width:innerWidth,scroll:document.documentElement.scrollWidth})');if(overflow.scroll>overflow.width+1)throw Error('Mobile overflow '+JSON.stringify(overflow));checks.push('mobile no horizontal overflow');
 await evaluate('(()=>{const s=document.querySelector("#review-version");s.value="0";s.dispatchEvent(new Event("change",{bubbles:true}));s.scrollIntoView({block:"center"})})()');await wait(textHas('该版本尚无评审结果'),'null-review version');await screenshot('10-mobile-old-version');
 await clickText('编辑后重新评审');await wait('!!document.querySelector("textarea[aria-label=编辑正文]")','mobile editor');await screenshot('11-mobile-editor');await input('textarea[aria-label=编辑正文]','## 开始行动\n\nREVISE_ME 请解释得更清楚。\n\n保留这一段，不要重写。');await clickText('保存新版本并评审');await wait(textHas('评审中'),'mobile review begins');
 await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await sleep(900);await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
 await wait(textHas('文本评审通过'),'GET recovers after real network interruption',30000);await wait(textHas('配图待重试'),'terminal after network interruption');await send('Page.reload');await wait(textHas('全局版本 v3'),'mobile refresh restores latest version');await screenshot('12-mobile-restored');

 const safe=await evaluate(`(async()=>{const {safeMarkdown}=await import('/src/utils/safeMarkdown.ts');const html=safeMarkdown('<script>window.A2_BAD=true</script><a href="javascript:alert(1)" onclick="alert(2)">link</a><svg onload="alert(3)"></svg>');return !/onclick|javascript:|<script|<svg/.test(html)&&!window.A2_BAD})()`);if(!safe)throw Error('Markdown unsafe');checks.push('markdown strips executable HTML');
 // Terminal pages must have no background polling after navigation/unmount.
 const before=network.filter(x=>x.url?.includes('/interventions')).length;await sleep(4500);const after=network.filter(x=>x.url?.includes('/interventions')).length;if(after!==before)throw Error('Terminal polling leak');checks.push('terminal polling cleaned');
 writeFileSync(resolve(out,'result.json'),JSON.stringify({fixturePrefix,status:'PASS',scope:'real Chrome + actual Spring HTTP/MySQL/Redis; cloud providers mocked',checks,errors,networkErrors:network.filter(x=>x.status>=400||x.error)},null,2));console.log('Browser PASS '+checks.length+' checks; errors '+errors.length);
}catch(e){await screenshot('failure').catch(()=>{});writeFileSync(resolve(out,'result.json'),JSON.stringify({status:'FAIL',error:e.stack,checks,errors},null,2));console.error(e);process.exitCode=1}
finally{writeFileSync(resolve(out,'case-evolution.json'),JSON.stringify(cases,null,2));writeFileSync(resolve(out,'network.json'),JSON.stringify(network,null,2));writeFileSync(resolve(out,'console.json'),JSON.stringify(errors,null,2));if(ws?.readyState===1){await send('Browser.close',{},null).catch(()=>{});ws.close()}else chrome.kill()}
