import {createHash,randomUUID} from 'node:crypto';
import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const info=JSON.parse(readFileSync(process.argv[2],'utf8'));
const stamp=new Date().toISOString().replace(/[:.]/g,'-');
const fixturePrefix='browser-'+stamp.toLowerCase();
const out=resolve(info.out,'browser-'+stamp);mkdirSync(out,{recursive:true});
const profile=resolve(info.work,'chrome-profile-'+stamp);mkdirSync(profile,{recursive:true});
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','--disable-extensions','about:blank'],{windowsHide:true,stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let ws,sessionId,seq=0;let faultInjected=false;const pending=new Map(),events=[],network=[],errors=[],checks=[],cases=[];
function send(method,params={},session=sessionId){return new Promise((ok,no)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);no(Error('CDP timeout '+method))},30000);pending.set(id,{ok,no,timer});ws.send(JSON.stringify({id,method,params,...(session?{sessionId:session}:{})}));})}
async function evaluate(expression){expression=expression.replaceAll('/api/article/uncertain-case/','/api/article/'+fixturePrefix+'-uncertain/');const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
async function wait(expression,label,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression)){checks.push(label);return;}await sleep(150)}throw Error('UI timeout '+label+' '+await evaluate('document.body.innerText.slice(-2000)'))}
const textHas=s=>`document.body.innerText.includes(${JSON.stringify(s)})`;
async function clickText(s){const clicked=await evaluate(`(()=>{const x=[...document.querySelectorAll('button')].find(x=>x.innerText.replace(/\\s/g,'').includes(${JSON.stringify(s.replace(/\s/g,''))}));if(!x||x.disabled)return false;x.click();return true})()`);if(!clicked)throw Error('Button missing '+s)}
async function input(selector,value){await evaluate(`(()=>{const x=document.querySelector(${JSON.stringify(selector)});if(!x)throw Error('input missing');x.value=${JSON.stringify(value)};x.dispatchEvent(new Event('input',{bubbles:true}));x.dispatchEvent(new Event('change',{bubbles:true}))})()`)}
async function screenshot(name){if(await evaluate('location.pathname.startsWith("/article/")')){const snapshot=await evaluate('(async()=>{const p=location.pathname;return {article:await (await fetch("/api"+p)).json(),intervention:await (await fetch("/api"+p+"/interventions")).json()}})()');cases.push({name,...snapshot});}
await sleep(350);const p=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(resolve(out,name+'.png'),Buffer.from(p.data,'base64'))}
async function navigate(path){path=path.replace('/article/browser-recovering','/article/'+fixturePrefix+'-recovering').replace('/article/uncertain-case','/article/'+fixturePrefix+'-uncertain');await send('Page.navigate',{url:info.frontend+path});await wait('location.href === '+JSON.stringify(info.frontend+path)+' && document.readyState === "complete"','loaded '+path,120000)}
try{
 const ready=JSON.parse(readFileSync(resolve(info.work,'target/a2-http-ready.json'),'utf8'));if(ready.failedTests.length)throw Error('HTTP prerequisites failed: '+ready.failedTests);
 const recovered=fixturePrefix+'-recovering';
 const snapshotQuery="SELECT JSON_OBJECT('mainTitle',a.mainTitle,'content',a.content,'enabledImageMethods',a.enabledImageMethods,'payloadHash',c.payloadHash,'requestId',c.requestId) FROM article a JOIN article_call c ON a.taskId COLLATE utf8mb4_unicode_ci=c.taskId COLLATE utf8mb4_unicode_ci WHERE a.taskId='uncertain-case' AND c.stepId='IMAGE_PLAN' LIMIT 1;";
 const read=spawnSync('docker',['exec',info.prefix+'-mysql','mysql','-uroot','-pa2-test-only','--default-character-set=utf8mb4','--batch','--raw','--skip-column-names','ai_passage_creator','-e',snapshotQuery],{encoding:'utf8',windowsHide:true});if(read.status!==0)throw Error('Cannot read isolated uncertain fixture: '+read.stderr);const sample=JSON.parse(read.stdout);
 const values={mainTitle:sample.mainTitle,content:sample.content,enabledImageMethods:Array.isArray(sample.enabledImageMethods)?sample.enabledImageMethods:JSON.parse(sample.enabledImageMethods)};
 const keys=Object.keys(values),orders=[];for(const a of keys)for(const b of keys)for(const c of keys)if(new Set([a,b,c]).size===3)orders.push([a,b,c]);
 const payload=orders.map(order=>JSON.stringify(Object.fromEntries(order.map(k=>[k,values[k]])))).find(v=>createHash('sha256').update(v).digest('hex')===sample.payloadHash);if(!payload)throw Error('Fixture payload hash mismatch');
 const runId=randomUUID(),uncertain=fixturePrefix+'-uncertain',callId=createHash('sha256').update(runId+'\n'+sample.requestId+'\nIMAGE_PLAN\n'+payload).digest('hex');
 const sql=`USE ai_passage_creator;
 INSERT INTO article(taskId,userId,topic,mainTitle,subTitle,outline,content,fullContent,status,phase,userDescription,enabledImageMethods) SELECT '${recovered}',userId,topic,'恢复状态检查',subTitle,outline,content,fullContent,'RECOVERING','REVIEWING',userDescription,enabledImageMethods FROM article WHERE taskId='cancel-case';
 INSERT INTO article_review(taskId,reviewJson) SELECT '${recovered}',reviewJson FROM article_review WHERE taskId='cancel-case';
 INSERT INTO article_runtime(taskId,runId,userId,stateVersion,lastEventId,remainingMs,maxCalls,callsUsed,maxImageRetries,maxEstimatedCostMicros,reservedCostMicros) SELECT taskId,UUID(),userId,1,1,600000,12,1,3,5000000,100000 FROM article WHERE taskId='${recovered}';
 INSERT INTO article_event(taskId,seq,runId,type,payloadJson) SELECT taskId,1,runId,'RECOVERING',JSON_OBJECT('type','RECOVERING','seq',1,'runId',runId) FROM article_runtime WHERE taskId='${recovered}';`;
 const uncertainSql=`
 INSERT INTO article(taskId,userId,topic,mainTitle,subTitle,outline,content,fullContent,status,phase,userDescription,enabledImageMethods) SELECT '${uncertain}',userId,topic,mainTitle,subTitle,outline,content,fullContent,'EXTERNAL_UNCERTAIN',phase,userDescription,enabledImageMethods FROM article WHERE taskId='uncertain-case';
 INSERT INTO article_review(taskId,reviewJson) SELECT '${uncertain}',reviewJson FROM article_review WHERE taskId='uncertain-case';
 INSERT INTO article_runtime(taskId,runId,userId,stateVersion,lastEventId,remainingMs,maxCalls,callsUsed,maxImageRetries,imageRetriesUsed,maxEstimatedCostMicros,reservedCostMicros) SELECT '${uncertain}','${runId}',userId,1,1,remainingMs,maxCalls,callsUsed,maxImageRetries,imageRetriesUsed,maxEstimatedCostMicros,reservedCostMicros FROM article_runtime WHERE taskId='uncertain-case';
 INSERT INTO article_operation(taskId,requestId,payloadHash,action,requestJson,status,runId,phase,checkpointJson) SELECT '${uncertain}',requestId,payloadHash,action,requestJson,'EXTERNAL_UNCERTAIN','${runId}',phase,checkpointJson FROM article_operation WHERE taskId='uncertain-case' AND action='ACCEPT';
 INSERT INTO article_call(callId,taskId,requestId,stepId,provider,payloadHash,status,attempts,queryAttempts,reservedCostMicros,deadlineAt) SELECT '${callId}','${uncertain}',requestId,stepId,provider,payloadHash,'UNCERTAIN',attempts,queryAttempts,reservedCostMicros,deadlineAt FROM article_call WHERE taskId='uncertain-case' AND stepId='IMAGE_PLAN';
 INSERT INTO article_event(taskId,seq,runId,type,payloadJson) VALUES ('${uncertain}',1,'${runId}','EXTERNAL_UNCERTAIN',JSON_OBJECT('type','EXTERNAL_UNCERTAIN','seq',1,'runId','${runId}'));`;
 const seeded=spawnSync('docker',['exec','-i',info.prefix+'-mysql','mysql','-uroot','-pa2-test-only','--default-character-set=utf8mb4'],{input:sql+uncertainSql,encoding:'utf8',windowsHide:true});if(seeded.status!==0)throw Error(seeded.stderr);
 for(let i=0;i<120&&!existsSync(resolve(profile,'DevToolsActivePort'));i++)await sleep(250);
 const [port,path]=readFileSync(resolve(profile,'DevToolsActivePort'),'utf8').trim().split(/\r?\n/);
 ws=new WebSocket('ws://127.0.0.1:'+port+path);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.no(Error(JSON.stringify(m.error))):p.ok(m.result)}return}events.push(m);if(m.method==='Fetch.requestPaused'){faultInjected=true;void send('Fetch.failRequest',{requestId:m.params.requestId,errorReason:'ConnectionClosed'}).then(()=>send('Fetch.disable'));return;}if(m.method==='Runtime.exceptionThrown')errors.push(m.params);if(m.method==='Runtime.consoleAPICalled'&&['error','warning'].includes(m.params.type))errors.push({type:m.params.type,args:m.params.args.map(x=>x.value||x.description)});if(m.method==='Network.responseReceived')network.push({url:m.params.response.url,status:m.params.response.status,type:m.params.type});if(m.method==='Network.loadingFailed')network.push({requestId:m.params.requestId,error:m.params.errorText,canceled:m.params.canceled})};
 const target=await send('Target.createTarget',{url:'about:blank'},null);sessionId=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true},null)).sessionId;
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await navigate('/user/login');await wait('!!document.querySelector("input[placeholder=请输入账号]")','login form');await input('input[placeholder=请输入账号]','a2owner');await input('input[placeholder=请输入密码]','a2-local-only');await clickText('登录');await wait('!location.pathname.includes("/user/login")','real backend login');

 await navigate('/article/cancel-case');await wait(textHas('已取消，草稿保留'),'cancel terminal visible');await wait('!!document.querySelector(".runtime-panel")','runtime panel rendered');await evaluate('document.querySelector(".runtime-panel").scrollIntoView({block:"start"})');await screenshot('01-desktop-cancelled');
 await send('Page.reload');await wait(textHas('已取消，草稿保留'),'cancel restored after refresh');
 await navigate('/article/budget-case');await wait(textHas('预算已耗尽'),'budget terminal visible');await wait('!!document.querySelector(".runtime-panel")','runtime panel rendered');await evaluate('document.querySelector(".runtime-panel").scrollIntoView({block:"start"})');await screenshot('02-desktop-budget');
 await navigate('/article/browser-recovering');await wait(textHas('恢复中'),'recovering durable snapshot fixture');await wait('!!document.querySelector(".runtime-panel")','runtime panel rendered');await evaluate('document.querySelector(".runtime-panel").scrollIntoView({block:"start"})');await screenshot('03-desktop-recovering');
 await wait('sessionStorage.getItem("article-runtime-cursor:'+fixturePrefix+'-recovering") === "1"','durable SSE cursor consumed');
 await send('Fetch.enable',{patterns:[{urlPattern:'*/api/article/progress/*',requestStage:'Response'}]});await send('Page.reload');
 const restoreDeadline=Date.now()+15000;while(Date.now()<restoreDeadline&&!network.some(x=>x.url?.includes('/progress/'+recovered+'?cursor=1')))await sleep(200);
 if(!faultInjected||!network.some(x=>x.url?.includes('/progress/'+recovered+'?cursor=1')))throw Error('No actual SSE reconnect with persisted cursor');checks.push('real network disconnect reconnect carries cursor');
 await navigate('/article/uncertain-case');await wait(textHas('外部结果不确定'),'uncertain visible');await wait('!!document.querySelector(".runtime-panel")','runtime panel rendered');await evaluate('document.querySelector(".runtime-panel").scrollIntoView({block:"start"})');await screenshot('04-desktop-uncertain');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.reload');await wait(textHas('外部结果不确定'),'mobile uncertainty restored');await wait('!!document.querySelector(".runtime-panel")','runtime panel rendered');await evaluate('document.querySelector(".runtime-panel").scrollIntoView({block:"start"})');await screenshot('05-mobile-uncertain');
 const bounds=await evaluate('({width:innerWidth,scroll:document.documentElement.scrollWidth})');if(bounds.scroll>bounds.width+1)throw Error('Mobile overflow '+JSON.stringify(bounds));checks.push('mobile no horizontal overflow');
 const before=await evaluate('(async()=> (await (await fetch("/api/article/uncertain-case/runtime")).json()).data.callsUsed)()');await clickText('人工确认后重试');await wait(textHas('我已核对并接受可能重复收费的风险'),'explicit acknowledgement shown');await screenshot('06-mobile-retry-confirmation');
 await evaluate('document.querySelector(".ant-modal input[type=checkbox]").click()');await clickText('接受风险并重试');await wait('!document.querySelector(".ant-modal:not([style*=none])") || !document.body.innerText.includes("确认重新调用外部服务")','retry submitted');
 await wait('(async()=>{const d=(await (await fetch("/api/article/uncertain-case/runtime")).json()).data;return d.callsUsed === '+(before+1)+' && d.status === "EXTERNAL_UNCERTAIN"})()','real backend retry debits same run budget');
 await wait('!document.querySelector(".runtime-panel .ant-btn-loading")','retry UI action settled');await clickText('刷新状态');await wait('!document.querySelector(".ant-btn-loading")','fresh snapshot settled');await clickText('取消任务并保留草稿');await wait(textHas('已取消，草稿保留'),'real cancel operation completed');await screenshot('07-mobile-cancelled');
 await sleep(3000);const count=network.filter(x=>x.url?.includes('/runtime')||x.url?.includes('/interventions')).length;await sleep(3000);if(network.filter(x=>x.url?.includes('/runtime')||x.url?.includes('/interventions')).length!==count)throw Error('Terminal polling leak');checks.push('terminal streams and polling cleaned');
 await navigate('/article/browser-old');await wait(textHas('这篇文章暂无评审记录'),'old article remains compatible');await screenshot('08-mobile-old-article');
 writeFileSync(resolve(out,'result.json'),JSON.stringify({status:'PASS',checks,errors,networkErrors:network.filter(x=>x.status>=400||x.error),scope:'Actual Chrome with real Spring/MySQL/Redis HTTP; cloud mocked. Recovering visual uses explicitly seeded persisted fixture; actual recovery is separately proven by process tests.'},null,2));console.log('A3 browser PASS '+checks.length+' checks');
}catch(e){await screenshot('failure').catch(()=>{});writeFileSync(resolve(out,'result.json'),JSON.stringify({status:'FAIL',error:e.stack,checks,errors},null,2));console.error(e);process.exitCode=1}
finally{writeFileSync(resolve(out,'console.json'),JSON.stringify(errors,null,2));writeFileSync(resolve(out,'network.json'),JSON.stringify(network,null,2));writeFileSync(resolve(out,'snapshots.json'),JSON.stringify(cases,null,2));try{await send('Browser.close',{},null)}catch{}ws?.close();chrome.kill();console.log(out)}
