import {createHash,randomUUID} from 'node:crypto';
import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
const info=JSON.parse(readFileSync(process.argv[2],'utf8'));
const stamp=new Date().toISOString().replace(/[:.]/g,'-');
const account='a4'+Date.now();
const fixturePrefix='browser-'+stamp.toLowerCase();
const out=resolve(info.out,'browser-'+stamp);mkdirSync(out,{recursive:true});
const profile=resolve(info.work,'chrome-profile-'+stamp);mkdirSync(profile,{recursive:true});
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','--disable-extensions','about:blank'],{windowsHide:true,stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let ws,sessionId,seq=0;let faultInjected=false;const pending=new Map(),events=[],network=[],errors=[],checks=[],cases=[];
function send(method,params={},session=sessionId){return new Promise((ok,no)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);no(Error('CDP timeout '+method))},30000);pending.set(id,{ok,no,timer});ws.send(JSON.stringify({id,method,params,...(session?{sessionId:session}:{})}));})}
async function evaluate(expression){expression=expression.replaceAll('a4browser',account);const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
async function wait(expression,label,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression)){checks.push(label);return;}await sleep(150)}throw Error('UI timeout '+label+' '+await evaluate('document.body.innerText.slice(-2000)'))}
const textHas=s=>`document.body.innerText.includes(${JSON.stringify(s)})`;
async function clickText(s){const clicked=await evaluate(`(()=>{const x=[...document.querySelectorAll('button')].find(x=>x.innerText.replace(/\\s/g,'').includes(${JSON.stringify(s.replace(/\s/g,''))}));if(!x||x.disabled)return false;x.click();return true})()`);if(!clicked)throw Error('Button missing '+s)}
async function input(selector,value){await evaluate(`(()=>{const root=document.querySelector(${JSON.stringify(selector)});const x=root?.matches('input,textarea')?root:root?.querySelector('input,textarea');if(!x)throw Error('input missing');x.value=${JSON.stringify(value)};x.dispatchEvent(new Event('input',{bubbles:true}));x.dispatchEvent(new Event('change',{bubbles:true}))})()`)}
async function screenshot(name){if(await evaluate('location.pathname.startsWith("/article/")')){const snapshot=await evaluate('(async()=>{const p=location.pathname;return {article:await (await fetch("/api"+p)).json(),intervention:await (await fetch("/api"+p+"/interventions")).json()}})()');cases.push({name,...snapshot});}
await sleep(350);const p=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(resolve(out,name+'.png'),Buffer.from(p.data,'base64'))}
async function navigate(path){await send('Page.navigate',{url:info.frontend+path});await wait('location.href === '+JSON.stringify(info.frontend+path)+' && document.readyState === "complete"','loaded '+path,120000)}
function control(scenario){const script='fetch("http://localhost:3333/control",{method:"POST",body:'+JSON.stringify(JSON.stringify({scenario,origin:info.frontend}))+'}).then(r=>r.json()).then(console.log)';const r=spawnSync('docker',['exec',info.prefix+'-provider','node','-e',script],{encoding:'utf8',windowsHide:true});if(r.status)throw Error(r.stderr)}
function check(ok,label){if(!ok)throw Error(label);checks.push(label)}
async function snapshot(){return evaluate('(async()=>{const id=location.pathname.split("/").pop();return (await (await fetch("/api/article/"+id+"/interventions")).json()).data})()')}
async function create(topic,scenario){control(scenario);await navigate('/create');await wait('!!document.querySelector(".topic-textarea")','creation page');await input('.topic-textarea',topic);await evaluate('[...document.querySelectorAll("label")].find(x=>x.innerText.trim()==="Pexels").querySelector("input").click()');await wait('!document.querySelector(".create-btn").disabled','create enabled');await clickText('开始创作');await wait(textHas('确认并生成大纲'),'titles generated',60000);await wait('!!document.querySelector(".title-option input")','title control ready');await evaluate('document.querySelector(".title-option input").click()');await input('textarea','面向非技术新手；保留无关段落，不编造数字或归因');await screenshot(scenario+'-title');await send('Page.reload');await sleep(700);await wait(textHas('确认并生成大纲'),'title selection refresh restored');await wait('!!document.querySelector(".title-option input")','title control ready');await evaluate('document.querySelector(".title-option input").click()');await input('textarea','面向非技术新手；保留无关段落，不编造数字或归因');await clickText('确认并生成大纲');await wait(textHas('确认并生成正文'),'outline ready',60000);await screenshot(scenario+'-outline');await clickText('确认并生成正文');await wait('!location.pathname.endsWith("create") && location.pathname.startsWith("/article/")','detail route',60000);}
try{
 for(let i=0;i<120&&!existsSync(resolve(profile,'DevToolsActivePort'));i++)await sleep(250);
 const [port,path]=readFileSync(resolve(profile,'DevToolsActivePort'),'utf8').trim().split(/\r?\n/);
 ws=new WebSocket('ws://127.0.0.1:'+port+path);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.no(Error(JSON.stringify(m.error))):p.ok(m.result)}return}events.push(m);if(m.method==='Fetch.requestPaused'){faultInjected=true;void send('Fetch.failRequest',{requestId:m.params.requestId,errorReason:'ConnectionClosed'}).then(()=>send('Fetch.disable'));return;}if(m.method==='Runtime.exceptionThrown')errors.push(m.params);if(m.method==='Runtime.consoleAPICalled'&&['error','warning'].includes(m.params.type))errors.push({type:m.params.type,args:m.params.args.map(x=>x.value||x.description)});if(m.method==='Network.responseReceived')network.push({url:m.params.response.url,status:m.params.response.status,type:m.params.type});if(m.method==='Network.loadingFailed')network.push({requestId:m.params.requestId,error:m.params.errorText,canceled:m.params.canceled})};
 const target=await send('Target.createTarget',{url:'about:blank'},null);sessionId=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true},null)).sessionId;
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});

 await navigate('/user/login');await wait('!!document.querySelector("input[placeholder=请输入账号]")','login form');
 const reg=await evaluate('(async()=>{return (await (await fetch("/api/user/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userAccount:"a4browser",userPassword:"a4-local-only",checkPassword:"a4-local-only"})})).json()).code})()');check(reg===0,'registered through real HTTP');
 const quota=spawnSync('docker',['exec',info.prefix+'-mysql','mysql','-uroot','-pa2-test-only','ai_passage_creator','-e',`UPDATE user SET quota=100 WHERE userAccount='${account}'`],{encoding:'utf8',windowsHide:true});if(quota.status)throw Error(quota.stderr);
 await input('input[placeholder=请输入账号]','a4browser');await input('input[placeholder=请输入密码]','a4-local-only');await clickText('登录');await wait('!location.pathname.includes("/user/login")','login');
 await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:resolve(out,'downloads'),eventsEnabled:true},null);
 await create('周末散步中的小发现','PASS');await wait(textHas('图文任务已完成'),'normal complete',60000);await screenshot('01-normal-complete');await clickText('导出Markdown');await sleep(1200);check(existsSync(resolve(out,'downloads')),'export created');const markdownFiles=readdirSync(resolve(out,'downloads')).filter(x=>x.endsWith('.md'));check(markdownFiles.length===1,'one Markdown file downloaded');const markdownBytes=readFileSync(resolve(out,'downloads',markdownFiles[0]));check(markdownBytes.toString('utf8').includes('周末散步中的小发现')&&markdownBytes.toString('utf8').includes('/api/images/'),'Markdown contains article and authenticated local image reference');writeFileSync(resolve(out,'markdown-export.json'),JSON.stringify({status:'PASS',bytes:markdownBytes.length,sha256:createHash('sha256').update(markdownBytes).digest('hex'),scope:'Actual browser download inspected; file retained only in ignored downloads directory'},null,2));
 await create('普通人如何用 AI 提升工作效率','REVISE');await wait(textHas('图文任务已完成'),'revision complete',60000);let view=await snapshot();check(view.reviewTrace.currentVersion===1,'one revision persisted');check(view.reviewTrace.versions[0].content.includes('保留这一段')&&view.reviewTrace.versions[1].content.includes('保留这一段'),'unrelated paragraph retained');await screenshot('02-revised');
 await create('给新手解释数据备份','LIMIT');await wait(textHas('本轮自动修订 2/2'),'two revision limit',60000);view=await snapshot();check(view.reviewTrace.stopReason==='REVISION_LIMIT','hard limit stops for human');await wait(textHas('待人工处理'),'stable human-review state');await screenshot('03-limit');
 await clickText('人工接受并继续配图');await wait('!!document.querySelector(".ant-modal input[type=checkbox]")','accept confirmation');await evaluate('document.querySelector(".ant-modal input[type=checkbox]").click()');await clickText('确认接受并继续配图');await wait(textHas('图文任务已完成'),'human accept continues media',60000);await screenshot('04-human-accepted');
 await create('整理书桌的三个步骤','MANUAL');await wait(textHas('编辑后重新评审'),'manual editing available',60000);await clickText('编辑后重新评审');await wait('!!document.querySelector(".ant-modal textarea")','editor');await input('.ant-modal textarea',"## 开始行动\n\n人工修改完成：先整理一件物品，记录步骤。\n\n保留这一段，不要重写。");await clickText('保存新版本并评审');await wait(textHas('图文任务已完成'),'edited draft completed',60000);view=await snapshot();check(view.reviewTrace.currentVersion===1,'editing appended global version');await screenshot('05-edited');
 await create('第一次制作旅行清单','IMAGE_FAIL');await wait(textHas('图片暂缺'),'image failure retained body',60000);view=await snapshot();const before=JSON.stringify(view.reviewTrace);await screenshot('06-image-failed');await clickText('重试 image-');await wait(textHas('图文任务已完成'),'single image retry completed',60000);check(JSON.stringify((await snapshot()).reviewTrace)===before,'image retry preserves review versions');await screenshot('07-image-retry');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.reload');await sleep(700);await wait(textHas('图文任务已完成'),'mobile refresh complete');check(await evaluate('document.documentElement.scrollWidth<=390'),'mobile no overflow');await screenshot('08-mobile-complete');
 writeFileSync(resolve(out,'result.json'),JSON.stringify({status:'PASS',checks,errors,networkErrors:network.filter(x=>x.status>=400||x.error),scope:'Actual packaged JAR + built Vue/Nginx + Compose MySQL/Redis; all tasks created through normal UI, local HTTP cloud fixture'},null,2));console.log('A4 browser PASS '+checks.length);
}catch(e){await screenshot('failure').catch(()=>{});writeFileSync(resolve(out,'result.json'),JSON.stringify({status:'FAIL',error:e.stack,checks,errors},null,2));console.error(e);process.exitCode=1}
finally{writeFileSync(resolve(out,'console.json'),JSON.stringify(errors,null,2));writeFileSync(resolve(out,'network.json'),JSON.stringify(network,null,2));writeFileSync(resolve(out,'snapshots.json'),JSON.stringify(cases,null,2));try{await send('Browser.close',{},null)}catch{}ws?.close();chrome.kill();console.log(out)}
