import {spawnSync} from 'node:child_process';import {mkdirSync,readFileSync,writeFileSync,copyFileSync,readdirSync} from 'node:fs';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),mode=process.argv[2];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cmd(args,input){const r=spawnSync('docker',args,{cwd:root,input,encoding:'utf8',windowsHide:true,timeout:180000,maxBuffer:16e6});if(r.status!==0)throw Error(args.slice(0,4).join(' ')+' '+r.stderr);return r.stdout.trim();}
if(mode==='stop'){const info=JSON.parse(readFileSync(process.argv[3]));if(!/^a4-install-[\dtz-]+$/.test(info.prefix))throw Error('Not an A4 project');writeFileSync(resolve(info.out,'compose-final.json'),cmd(['compose','-p',info.prefix,'-f',info.compose,'ps','--all','--format','json']));writeFileSync(resolve(info.out,'application.log'),cmd(['logs',info.prefix+'-backend']));cmd(['compose','-p',info.prefix,'-f',info.compose,'down','--volumes']);info.cleanedUp=true;writeFileSync(process.argv[3],JSON.stringify(info,null,2));console.log('Dedicated A4 project cleaned');
}else if(mode==='start'){
 const build=resolve(process.argv[3]),front=resolve(process.argv[4]),kind=process.argv[5]||'fresh',stamp=new Date().toISOString().replace(/[:.]/g,'-').toLowerCase(),prefix='a4-install-'+stamp,work=resolve(root,'tools/dev-harness/.work',prefix),out=resolve(root,'artifacts/a4/runs',prefix);mkdirSync(work,{recursive:true});mkdirSync(out,{recursive:true});
 writeFileSync(resolve(work,'isolated.env'),'MYSQL_ROOT_PASSWORD=a2-test-only\nDASHSCOPE_API_KEY=isolated-unused\nPEXELS_API_KEY=isolated-unused\nIMAGE_MODEL_API_KEY=\n');
 const cfg=JSON.parse(cmd(['compose','--env-file',resolve(work,'isolated.env'),'-f','docker-compose.yml','config','--format','json']));delete cfg.name;if(kind==='upgrade')cfg.services.mysql.volumes=cfg.services.mysql.volumes.filter(v=>!/(06_review|07_intervention|08_runtime|09_local_images|10_image_providers)\.sql$/.test(v.target));
 for(const [name,s] of Object.entries(cfg.services)){s.container_name=prefix+'-'+name;s.restart='no';delete s.build;s.mem_limit=name==='backend'?'2g':name==='mysql'?'1g':'256m';s.cpus=2;delete s.logging;delete s.ports;}
 cfg.networks['app-network'].name=prefix+'-net';cfg.networks['app-network'].internal=true;cfg.networks['ui-network']={name:prefix+'-ui',driver:'bridge'};cfg.services.frontend.networks=['app-network','ui-network'];for(const [name,v] of Object.entries(cfg.volumes))v.name=prefix+'-'+name;
 const jar=readdirSync(resolve(build,'target')).find(x=>x.endsWith('.jar')&&!x.endsWith('.original'));if(!jar)throw Error('Build JAR missing');copyFileSync(resolve(build,'target',jar),resolve(work,'app.jar'));copyFileSync(resolve(root,'tools/dev-harness/a4-provider.mjs'),resolve(work,'a4-provider.mjs'));
 const plugin=resolve(work,'plugin/com/yupi/template/runtime');mkdirSync(plugin,{recursive:true});for(const f of readdirSync(resolve(build,'target/test-classes/com/yupi/template/runtime')).filter(f=>f.startsWith('A4MockProviderConfig')&&f.endsWith('.class')))copyFileSync(resolve(build,'target/test-classes/com/yupi/template/runtime',f),resolve(plugin,f));copyFileSync(resolve(build,'target/test-classes/application-a2-isolated.properties'),resolve(work,'plugin/application-a2-isolated.properties'));
 const maven='maven@sha256:65353f527c86cb23187c8233475713e15067e8d36220d18863c379680698fe85',node='node@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32';
 const runtimeImage=JSON.parse(readFileSync(resolve(root,'artifacts/a4/runtime-image.json')));if(runtimeImage.jarSha256!==createHash('sha256').update(readFileSync(resolve(work,'app.jar'))).digest('hex'))throw Error('Runtime image JAR mismatch');
 Object.assign(cfg.services.backend,{image:runtimeImage.imageId,working_dir:'/work',entrypoint:['java'],command:['-Dloader.path=/work/plugin','-cp','/work/app.jar','org.springframework.boot.loader.launch.PropertiesLauncher','--spring.profiles.active=a2-isolated,a4-isolated','--server.port=8123','--article.runtime.enabled=true','--nano-banana.api-key=','--article.images.demo.remote-enabled=true'],volumes:[{type:'bind',source:work,target:'/work'},{type:'volume',source:'image-data',target:'/data/images'}],environment:{A4_ISOLATED:'true',A3_PROVIDER_URL:'http://provider:3333',A2_TEST_DB_URL:'jdbc:mysql://mysql:3306/ai_passage_creator?useUnicode=true&characterEncoding=UTF-8',A2_REDIS_HOST:'redis',ARTICLE_STORAGE_LOCAL_ROOT:'/data/images',ARTICLE_STORAGE_TYPE:'local'},healthcheck:{test:['CMD','curl','-f','http://localhost:8123/api/health/'],interval:'5s',timeout:'3s',retries:24,start_period:'20s'}});
 cfg.services.provider={image:node,container_name:prefix+'-provider',command:['node','/work/a4-provider.mjs'],volumes:[{type:'bind',source:work,target:'/work'}],networks:['app-network'],mem_limit:'256m'};
 const nginx=readFileSync(resolve(root,'frontend/nginx.conf'),'utf8');writeFileSync(resolve(work,'nginx.conf'),nginx);writeFileSync(resolve(front,'frontend/dist/a4-image.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#d4eddc"/><text x="60" y="180" font-size="25">A4 MOCK — fixed illustration</text></svg>');
 Object.assign(cfg.services.frontend,{image:cmd(['image','inspect','ai-passage-frontend:latest','--format','{{.Id}}']),ports:[{target:80,host_ip:'127.0.0.1'}],volumes:[{type:'bind',source:resolve(front,'frontend/dist'),target:'/usr/share/nginx/html',read_only:true},{type:'bind',source:resolve(work,'nginx.conf'),target:'/etc/nginx/conf.d/default.conf',read_only:true}]});
 const compose=resolve(work,'compose.json');writeFileSync(compose,JSON.stringify(cfg,null,2));const composeCmd=(...args)=>cmd(['compose','-p',prefix,'-f',compose,...args]);composeCmd('up','-d','mysql','redis','provider');
 let ready=false;for(let i=0;i<90;i++){try{if(cmd(['inspect',prefix+'-mysql','--format','{{.State.Health.Status}}'])==='healthy' && cmd(['exec',prefix+'-mysql','mysql','-uroot','-pa2-test-only','-h127.0.0.1','-e','USE ai_passage_creator; SELECT COUNT(*) FROM article;'])){ready=true;break}}catch{}await sleep(1000)}if(!ready)throw Error('MySQL schema not ready');
 const sql=q=>cmd(['exec','-i',prefix+'-mysql','mysql','-uroot','-pa2-test-only','--default-character-set=utf8mb4','--batch','--raw','--skip-column-names','ai_passage_creator'],q);
 if(kind==='upgrade')sql("INSERT INTO article(taskId,userId,topic,content,status) VALUES ('a4-old',1,'synthetic old article','preserved old content','COMPLETED');");
 if(kind==='upgrade'&&sql("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='ai_passage_creator' AND table_name='article_generated_image'")!=='0')throw Error('Upgrade fixture already has local image table');
 const migrations=['add_article_review.sql','add_article_intervention.sql','add_article_runtime.sql','add_local_image_storage.sql','add_image_providers.sql'];for(let n=0;n<2;n++)for(const f of migrations){sql(readFileSync(resolve(root,'sql',f),'utf8'));if(kind==='upgrade'&&n===0&&f==='add_image_providers.sql')sql("INSERT INTO article_image_profile(taskId,method,profileJson) VALUES ('a4-old','DOUBAO',JSON_OBJECT('provider','doubao','model','preserved-seedream-model')); INSERT INTO article_image_metadata(cacheKey,metadataJson) VALUES (REPEAT('b',64),JSON_OBJECT('provider','doubao','model','preserved-seedream-model'));");if(kind==='upgrade'&&n===0&&f==='add_article_review.sql')sql("INSERT INTO article_review(taskId,reviewJson) VALUES ('a4-old','{\"currentVersion\":2}');");if(kind==='upgrade'&&n===0&&f==='add_article_intervention.sql')sql("INSERT INTO article_operation(taskId,requestId,payloadHash,action,requestJson,status) VALUES ('a4-old','a4-old-operation',REPEAT('a',64),'ACCEPT','{}','COMPLETED'); INSERT INTO article_intervention(taskId,revision,mediaJson) VALUES ('a4-old',3,'{\"slots\":[]}');");}
 if(kind==='upgrade'&&sql("SELECT content FROM article WHERE taskId='a4-old';")!=='preserved old content')throw Error('Old content lost');
 if(kind==='upgrade'&&(sql("SELECT JSON_EXTRACT(reviewJson,'$.currentVersion') FROM article_review WHERE taskId='a4-old'")!=='2'||sql("SELECT status FROM article_operation WHERE taskId='a4-old'")!=='COMPLETED'||sql("SELECT revision FROM article_intervention WHERE taskId='a4-old'")!=='3'))throw Error('A1/A2 history changed');
 writeFileSync(resolve(out,'migration.json'),JSON.stringify({kind,appliedTwice:migrations,oldDataPreserved:kind==='upgrade',reviewVersion:kind==='upgrade'?2:null,operationStatus:kind==='upgrade'?'COMPLETED':null,interventionRevision:kind==='upgrade'?3:null,scope:'Own Compose named volumes; original volumes untouched'},null,2));composeCmd('up','-d','backend','frontend');
 const port=composeCmd('port','frontend','80').split(':').at(-1),info={prefix,work,out,compose,frontend:'http://127.0.0.1:'+port,backend:'http://127.0.0.1:'+port,kind,build,front,jarSha256:createHash('sha256').update(readFileSync(resolve(work,'app.jar'))).digest('hex'),cleanedUp:false};writeFileSync(resolve(out,'live.json'),JSON.stringify(info,null,2));console.log(resolve(out,'live.json'));
}else throw Error('start <backend work> <frontend work> [fresh|upgrade] | stop <live.json>');
