import {spawnSync} from 'node:child_process';import {readFileSync,writeFileSync,readdirSync,existsSync,mkdirSync} from 'node:fs';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),stamp=new Date().toISOString().replace(/[:.]/g,'-'),out=resolve(root,'artifacts/a4/runs/gate-'+stamp);mkdirSync(out,{recursive:true});const results=[];const installOnly=process.argv.includes('--install-only'),resumeHttp=process.argv.includes('--resume-http');const acceptance=(installOnly||resumeHttp)?JSON.parse(readFileSync(resolve(root,'artifacts/a4/acceptance-runs.json'))):{runs:{}};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function run(name,script,args=[],allowed=[],env={}){const start=Date.now();const r=spawnSync(process.execPath,[resolve(root,'tools/dev-harness',script),...args],{cwd:root,env:{...process.env,...env},encoding:'utf8',windowsHide:true,timeout:3600000,maxBuffer:16e6});writeFileSync(resolve(out,name+'.txt'),(r.stdout||'')+(r.stderr||''));results.push({name,command:['node','tools/dev-harness/'+script,...args],exitCode:r.status,durationMs:Date.now()-start,status:r.status===0?'PASS':allowed.includes(r.status)?'BASELINE_FAILURE':'FAIL'});writeFileSync(resolve(out,'commands.json'),JSON.stringify(results,null,2));if(r.status!==0&&!allowed.includes(r.status))throw Error(name+' failed; see '+out);console.log(name+': '+r.status);return r.stdout;}
let build,front;
function newest(suffix){return readdirSync(resolve(root,'artifacts/a3/runs')).filter(x=>x.endsWith(suffix)).sort().at(-1)}
function livePath(text){const m=text.match(/[A-Z]:[^\r\n]*live\.json/);if(!m)throw Error('live.json not emitted');return m[0]}
async function ready(info){for(let i=0;i<600;i++){const f=resolve(info.work,'target/a2-http-ready.json');if(existsSync(f)){const r=JSON.parse(readFileSync(f));if(r.failedTests.length)throw Error('HTTP assertions failed '+r.failedTests);return}await sleep(1000)}throw Error('HTTP ready deadline')}
try{
 run('candidate','a4-candidate.mjs',['verify']);const sourceId=JSON.parse(readFileSync(resolve(root,'artifacts/a4/candidate.json'))).sourceId;if((installOnly||resumeHttp)&&acceptance.sourceId!==sourceId)throw Error('Resume source differs');acceptance.sourceId=sourceId;if(resumeHttp){build=acceptance.runs.mock.work;front={work:acceptance.runs.front.work};}if(!installOnly){if(!resumeHttp){run('mock','run.mjs',['a3-mock']);const mock=JSON.parse(readFileSync(resolve(root,'artifacts/a3/runs',newest('Z'),'summary.json')));build=mock.work;acceptance.runs.mock={out:resolve(root,'artifacts/a3/runs',newest('Z')),work:build,required:['summary.json']};
 run('runtime-image','a4-runtime-image.mjs',[build]);acceptance.runs.runtimeImage={out:JSON.parse(readFileSync(resolve(root,'artifacts/a4/runtime-image.json'))).out,required:['result.json']};
 const prior=readdirSync(resolve(root,'artifacts/a3/runs')).filter(x=>x.endsWith('-live')).sort().reverse().map(x=>resolve(root,'artifacts/a3/runs',x,'live.json')).find(existsSync);if(!prior)throw Error('Isolated frontend dependency snapshot missing');
 run('frontend','a3-front.mjs',[prior],[1]);front=JSON.parse(readFileSync(resolve(root,'artifacts/a3/runs',newest('-front'),'summary.json')));if(front.results.some(r=>r.task!=='lint:check'&&r.status!=='PASS'))throw Error('Frontend regression');
 const sseOut=run('sse','a4-sse.mjs',[front.work,prior]).trim().split(/\r?\n/).at(-1);acceptance.runs.sse={out:sseOut,required:['result.json']};acceptance.runs.front={out:resolve(root,'artifacts/a3/runs',newest('-front')),work:front.work,required:['summary.json']};const contextOut=run('context','a4-context.mjs',[build],[1]).trim().split(/\r?\n/).at(-1);acceptance.runs.context={out:contextOut,required:['result.json']};run('store','a3-store.mjs');const storeId=newest('-store');acceptance.runs.store={out:resolve(root,'artifacts/a3/runs',storeId),work:resolve(root,'tools/dev-harness/.work/a3-store-'+storeId.replace(/-store$/,'')),required:['com.yupi.template.runtime.A3StoreIT.txt']};}let live=livePath(run('http-start','a3-live.mjs',['start']));try{await ready(JSON.parse(readFileSync(live)));run('http-browser','a3-browser.mjs',[live]);const hi=JSON.parse(readFileSync(live));acceptance.runs.http={out:hi.out,work:hi.work,required:['com.yupi.template.intervention.A3HttpIT.txt']};acceptance.runs.runtimeBrowser={out:resolve(hi.out,readdirSync(hi.out).filter(x=>x.startsWith('browser-')).sort().at(-1)),required:['result.json']};}finally{run('http-stop','a3-live.mjs',['stop',live]);}
 live=livePath(run('process-start','a3-live.mjs',['start'],[],{A3_PROCESS_ISOLATED:'true'}));try{run('fault','a3-fault.mjs',[live]);const fi=JSON.parse(readFileSync(live));acceptance.runs.fault={out:fi.out,work:fi.work,required:['fault-result.json']};}finally{run('process-stop','a3-process-clean.mjs',[live]);}
 writeFileSync(resolve(root,'artifacts/a4/acceptance-runs.json'),JSON.stringify(acceptance,null,2));}else{build=acceptance.runs.mock.work;front={work:acceptance.runs.front.work};}let live;
 for(const kind of ['fresh','upgrade']){live=livePath(run(kind+'-start','a4-compose.mjs',['start',build,front.work,kind]));try{run(kind+'-install','a4-install-check.mjs',[live]);const ci=JSON.parse(readFileSync(live));acceptance.runs[kind]={out:ci.out,required:['install-check.json']};acceptance.jar={path:resolve(ci.work,'app.jar'),sha256:ci.jarSha256};acceptance.frontend={work:front.work};if(kind==='fresh'){run('e2e-browser','a4-browser.mjs',[live]);const br=resolve(ci.out,readdirSync(ci.out).filter(x=>x.startsWith('browser-')).sort().at(-1));acceptance.runs.browser={out:br,required:['result.json']};run('local-http','a4-local-http.mjs',[live,resolve(br,'snapshots.json')]);acceptance.runs.localStorage={out:resolve(ci.out,'local-storage'),required:['result.json']};run('offline-browser','a4-offline-browser.mjs',[live,resolve(ci.out,'local-storage/result.json')]);acceptance.runs.offline={out:resolve(ci.out,readdirSync(ci.out).filter(x=>x.startsWith('browser-')).sort().at(-1)),required:['result.json']};run('visual-supplement','a4-inspect.mjs',[live,resolve(br,'snapshots.json')]);acceptance.runs.visual={out:resolve(ci.out,readdirSync(ci.out).filter(x=>x.startsWith('browser-')).sort().at(-1)),required:['result.json']};run('default-ui','a4-default-browser.mjs',[live]);acceptance.runs.defaultLocal={out:resolve(ci.out,readdirSync(ci.out).filter(x=>x.startsWith('browser-')).sort().at(-1)),required:['result.json']};run('demo-local-http','a4-local-http.mjs',[live,resolve(acceptance.runs.defaultLocal.out,'snapshots.json')]);run('demo-offline-browser','a4-offline-browser.mjs',[live,resolve(ci.out,'local-storage/result.json')]);acceptance.runs.offline={out:resolve(ci.out,readdirSync(ci.out).filter(x=>x.startsWith('browser-')).sort().at(-1)),required:['result.json']};run('degraded-ui','a4-degraded.mjs',[live]);acceptance.runs.degraded={out:resolve(ci.out,readdirSync(ci.out).filter(x=>x.startsWith('browser-')).sort().at(-1)),required:['result.json']};}}finally{run(kind+'-stop','a4-compose.mjs',['stop',live]);}}
 run('final-source','a4-candidate.mjs',['verify']);writeFileSync(resolve(root,'artifacts/a4/acceptance-runs.json'),JSON.stringify(acceptance,null,2));run('artifact-gate','a4-verify-evidence.mjs');writeFileSync(resolve(out,'result.json'),JSON.stringify({status:'ENGINEERING_CANDIDATE',results,visualReview:'REQUIRED: actually inspect produced screenshots',paidApi:'NOT_RUN',note:'Not A4 fully passed until explicitly authorized final-version paid smoke and visual review'},null,2));
}catch(e){writeFileSync(resolve(out,'failure.json'),JSON.stringify({error:e.stack,results},null,2));process.exitCode=1;console.error(e.message)}finally{if(acceptance.sourceId)writeFileSync(resolve(root,'artifacts/a4/acceptance-runs.json'),JSON.stringify(acceptance,null,2));console.log(out)}
