-- Additive, repeatable; run manually against the intended database after backup.
CREATE TABLE IF NOT EXISTS model_config (id VARCHAR(32) PRIMARY KEY, version INT NOT NULL, kind VARCHAR(10) NOT NULL, spec JSON NOT NULL, secret TEXT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, deleted BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS model_default (kind VARCHAR(10) PRIMARY KEY, configId VARCHAR(32) NOT NULL);
CREATE TABLE IF NOT EXISTS model_version (configId VARCHAR(32) NOT NULL, version INT NOT NULL, spec JSON NOT NULL, PRIMARY KEY(configId,version));
CREATE TABLE IF NOT EXISTS article_text_profile (taskId VARCHAR(64) PRIMARY KEY, spec JSON NOT NULL);
CREATE TABLE IF NOT EXISTS model_audit (id BIGINT AUTO_INCREMENT PRIMARY KEY, actor BIGINT NOT NULL, action VARCHAR(40) NOT NULL, configId VARCHAR(32) NOT NULL, version INT NOT NULL, createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS model_probe (requestId VARCHAR(36) PRIMARY KEY, actor BIGINT NOT NULL, configId VARCHAR(32) NOT NULL, version INT NOT NULL, status VARCHAR(32) NOT NULL, result JSON NULL, createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
