-- A4: retained generated bytes, no migration of existing images or user files.
CREATE TABLE IF NOT EXISTS article_generated_image (
 cacheKey char(64) PRIMARY KEY,
 taskId varchar(64) NOT NULL,
 imageBytes mediumblob NOT NULL,
 mimeType varchar(100) NOT NULL,
 createdAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_generated_task(taskId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
